### ISSUE TITLE
houdini_examples.hip opens with many errors and warnings in houdini 18.0.460

### ISSUE THREAD

**Issue by AlecBartsch** [AcademySoftwareFoundation/openvdb#1018]
The example houdini file provided at https://www.openvdb.org/download/ looks like it dates from 2017 and was created in houdini 15.5.680; based on the errors and warnings seen when opened it seems to be quite a bit out of sync with current houdini VDB nodes. I'm not sure which example networks in the file are potentially broken and which are fine. I've attached a text file with the full log output.

[errorOutput.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/6208565/errorOutput.txt)

**Comment by Idclip** [comment]
Thanks for reporting this @AlecBartsch - the file has now been updated to VDB 8.1/Houdini 18.5: https://github.com/AcademySoftwareFoundation/openvdb-website/pull/55
