### ISSUE TITLE
[BUG] Artifacts on Smooth Filter

### ISSUE THREAD

**Issue by mifth** [AcademySoftwareFoundation/openvdb#1104]
### Environment
**Operating System:** Windows 10
**Version / Commit SHA:** 8

### Describe the bug
I found that a Smooth Filter creates artifacts on a vdb grid which was created from polygons. I just added some boxes, converted them to a VDB Grid and applied smooth filter.

![image](https://user-images.githubusercontent.com/2251298/121822293-3f0e6200-cc96-11eb-8e4e-5d7cad3c3735.png)

Without the Smooth Fillter all looks fine.
![image](https://user-images.githubusercontent.com/2251298/121822310-5baa9a00-cc96-11eb-93fb-133905411488.png)

Here my example of the result. OBJ File.
[objects_test.zip](https://github.com/AcademySoftwareFoundation/openvdb/files/6644689/objects_test.zip)

Here is my VDB file without the Smooth Filter.
[vdb_out_0.zip](https://github.com/AcademySoftwareFoundation/openvdb/files/6644694/vdb_out_0.zip)

### To Reproduce
1. Load my file (vdb_out_0.vdb) as a grid.
2. Apply Smooth Filter like this:
```
openvdb::tools::Filter<openvdb::FloatGrid> lsf(*grid);
lsf.setGrainSize(1);
lsf.gaussian(3, 1);

```

And you will see artifacts.

You can also reproduce this issue with Houdini usin SmoothSDF Node. I assume it will show the same issue.

### Expected behavior
No Artifacts.

**Comment by mifth** [comment]
Another one note. When I converted the mesh from polygons to VDB I set HalfWidth = 6.0.

My code looked like this:
```
std::vector<openvdb::Vec3s> parseVerts;
std::vector<openvdb::Vec3I> parseTris;
std::vector<openvdb::Vec4I> parseQuads;

openvdb::math::Transform::Ptr xform = openvdb::math::Transform::createLinearTransform(py_vdb_data->voxelSize);
grid = openvdb::tools::meshToLevelSet<openvdb::FloatGrid>(*xform, parseVerts, parseTris, parseQuads, 6.0);
grid->setName("density");
```

**Comment by Idclip** [comment]
Hey @mifth, thanks for this. I believe that this is a problem with the original polygons->SDF conversion and not an issue with the `openvdb::tools::Filter` class. I've typically seen this when you have polygons which are intersecting *and* coplanar, which seems to be the case here.

In Houdini there is a node called the VDB Visualize Tree SOP. This lets you look at the topology of a VDB. Using this on the SDF created from your geometry (and removing redundant data) you'll observe some weird artefacts at the intersections of the coplanar faces:

<img src="https://user-images.githubusercontent.com/4256455/121884428-d1504d80-cd0a-11eb-82b1-ad710e766842.png" width=500>

The best way to fix these is typically to convert back to geometry then back to a SDF. This sounds counter intuitive, but by re-generating the mesh it ensures that artefacts like these are removed. This workflow is encapsulated by the tool in `openvdb/tools/LevelSetRebuild.h`

```
openvdb::math::Transform::Ptr xform = openvdb::math::Transform::createLinearTransform(py_vdb_data->voxelSize);
grid = openvdb::tools::meshToLevelSet<openvdb::FloatGrid>(*xform, parseVerts, parseTris, parseQuads, 6.0);

// rebuild the level set using the tools in LevelSetRebuild.h
grid = openvdb::tools::levelSetRebuild(*grid, 0.0, 6.0);

openvdb::tools::Filter<openvdb::FloatGrid> lsf(*grid);
lsf.setGrainSize(1);
lsf.gaussian(3, 1);

grid->setName("density");
```

This is obviously not ideal. In this trivial case you're unlikely to lose much information with the secondary conversion, but in cases where high fidelity is important you may find that you naturally lose some additional detail as you go back and forth between mesh and volume. I'm not confident in saying why `meshToLevelSet` is producing these issues yet, but I've seen it before and suspect it's to do with floating point tolerance distances with overlapping coplanar polygons.

**Comment by Idclip** [comment]
I should also mention that, in your case, were you to generate an SDF per box and then combine then with a `csgUnion` operation, this would most likely fix the issue you're seeing from the original conversion.

**Comment by mifth** [comment]
Hi @Idclip , thank you so much for this idea. I'll take into account the rebuild node.

I also found another one solution:

1.  Convert a mesh to a grid with halfSize=2.0
2. Dilate the grid to 3
3. Smooth the grid with the filter
4. Erode the grid to 3 (just to revert voxels back)

The result looks nice.
![image](https://user-images.githubusercontent.com/2251298/121892243-660b7900-cd14-11eb-8aa7-9e8b7c90f328.png)


But I don't know which variant is better/faster/proper. Rebuild halfSize=6.0 or Dilate/Erode withhalfSize=2.0? What do you think?

**Comment by mifth** [comment]
About the csgUnion is a good way but it will be much slower. as there could be tenths of unions/defferences.

**Comment by mifth** [comment]
Anyway, I'm closing the bug. Thank you.
