### ISSUE TITLE
[BUILD] NanoVDB building docs reports ToDo.md missing

### ISSUE THREAD

**Issue by skurmedel** [AcademySoftwareFoundation/openvdb#1111]
### Environment
**Operating System:** Ubuntu 20 WSL 2 (Windows 10)
**Version / Commit SHA:** 9b79bb0dd66a442149083c8093deefcb03f881c3
**CMake Version:** 3.16
**Compiler:** gcc 9

### Describe the problem
Last error from cmake is as follows:
```
-- DOXYGEN_EXECUTABLE = doxygen
-- Configuring done
CMake Error at docs/CMakeLists.txt:16 (add_custom_target):
  Cannot find source file:

    ToDo.md

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

Looking in the repo, I cannot see a ToDo.md in the docs folder.

### To Reproduce
1. Checkout repo openvdb, branch feature/nanovdb
2. mkdir build
3. cd build; cmake -DNANOVDB_BUILD_DOCS=true ..

### Additional context
(Add any other context about the problem here.)

**Comment by kmuseth** [comment]
Thanks - we'll fix this bug!
