### ISSUE TITLE
[BUILD] Can't import pyopenvdb in Windows 10

### ISSUE THREAD

**Issue by diegogangl** [AcademySoftwareFoundation/openvdb#1125]
### Environment
**Operating System:** Windows 10 / Python 3.9
**Version / Commit SHA:** VDB 8.0.1
**CMake Version:**  3.20.4
**Compiler:** msvc 2019

### Describe the problem
The Python module builds but can't be imported, as it fails to load some DLL

### To Reproduce

1. Build OpenVDB with the Python module option. 
2. Open a powershell or regular prompt at the folder where the pyd file is
3. Try to `import pyopenvdb`

### Tried

- Copying DLLs into the folder (`Half-2_5.dll`, `libzstd.dll`, `openvdb.dll` and `boost_python39-vc142-mt-gd-x64-1_76.dll`). I got these from the Dependencies tool.
- Also tried adding `snappy_64.dll`
- Appending the path to `sys.path`
- Adding the path with `os.add_dll_directory()`
- Look around the source code to figure out which dll is trying to find

No matter what I try I always get

```python
>>> import pyopenvdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed while importing pyopenvdb: The specified module could not be found.
```

I need to distribute the python module along with a project, so it needs to be portable (at least not require users to compile things). Is it possible to at least know which DLL is missing or where it's looking for it?

**Comment by diiigle** [comment]
Hi Diego,

There is the new [discussions forum](https://github.com/AcademySoftwareFoundation/openvdb/discussions) for questions right here on github.

To answer your question:
I would start with **dependencywalker** as this lists you all the *recursively* missing DLLs. I would suspect boost_python might also depend on other boost libraries.

**Comment by diegogangl** [comment]
Thanks @diiigle , I'll open a discussion over there.

**Comment by Idclip** [comment]
Hi @diegogangl,

How are you installing VDB dependencies (boost, tbb etc), are you using vcpkg? Can you also double check that the version of python you're launching is exactly the same as the version VDB has been compiled against (i.e. 3.9)?

**Comment by Idclip** [comment]
Closing, but please re-open if this is still an issue
