### ISSUE TITLE
[BUG] Understanding combineExtended on grids

### ISSUE THREAD

**Issue by frapit** [AcademySoftwareFoundation/openvdb#1127]
### Environment
**Operating System:** ubuntu18.04
**Version / Commit SHA:** 8.1
**Other:** g++ --std=c++17

### Describe the bug
I don't know if I am getting the concept but in the [combineExtended](https://www.openvdb.org/documentation/doxygen/classopenvdb_1_1v8__0_1_1tree_1_1Tree.html#a71140d5e67f0fce2c7fe0ae119db9711) method of a grid, I am not able do deactivate the voxel in the combine functor using the [CombineArgs](https://www.openvdb.org/documentation/doxygen/classopenvdb_1_1v8__0_1_1CombineArgs.html). `args.setResultIsActive(false)` should do this as per documentation.

When I use the [combine2Extended](https://www.openvdb.org/documentation/doxygen/classopenvdb_1_1v8__0_1_1tree_1_1Tree.html#a878302f18a7f23adac7da7a9fc5f7441) instead, The behavior is as I would expect. 

Consider this minimal example:
```
#include <openvdb/openvdb.h>
#include <iostream>
int main()
{
    openvdb::initialize();
    openvdb::FloatGrid::Ptr grid = openvdb::FloatGrid::create();
    openvdb::FloatGrid::Ptr grid_merge = openvdb::FloatGrid::create();
    openvdb::FloatGrid::Accessor accessor = grid->getAccessor();

    accessor.setValue({0, 0, 5}, 3.0f);
    accessor.setValue({0, 0, 4}, 4.0f);

    auto set_inactive = [](openvdb::CombineArgs<float>& args) {
        args.setResultIsActive(false);
        // args.setResult(1.0); // That works
    };
  
    std::cout << "Active voxel count grid: " << grid->activeVoxelCount() << "\n"; // 2
    std::cout << "Active voxel count merge: " << grid_merge->activeVoxelCount() << "\n"; // 0

    grid_merge->tree().combineExtended(grid->tree(), set_inactive);
    // grid_merge->tree().combine2Extended(grid_merge->tree(), grid->tree(), set_inactive);

    std::cout << "Active voxel count grid: " << grid->activeVoxelCount() << "\n"; // 0
    std::cout << "Active voxel count merge after: " << grid_merge->activeVoxelCount() << "\n"; // 2, but should be zero.
    return 0;
}

```

Inside the combine lambda I am deactivating all tiles but in the output of the last line you see that the two entries with a value are still active. On the other hand, if you use the combine2Extended instead, `activeVoxelCound` is zero for the `grid_merge` as expected.

I am wondering why the behavior is different and if this is intended for `combineExtended`. Setting anything regarding activeness in the lambda has no effect at all, I tried different combinations. The voxels with a value are always active.

Thanks!

**Comment by Idclip** [comment]
Hey @frapit I believe this is indeed a bug. When `combineExtended` processes a constant node in the destination grid (`grid_merge`) and a child node from the source grid (`grid`) it forwards the `CombineArgs` to an intermediate functor  `SwappedCombineOp`:

https://github.com/AcademySoftwareFoundation/openvdb/blob/a71f65ca26664719d41bd282683ad3d3be1be68d/openvdb/openvdb/Types.h#L541-L553

 `SwappedCombineOp` doesn't correctly forward the result of the active state. I believe the simple fix is:

```C++
    void operator()(CombineArgs<ValueType>& args)
    {
        CombineArgs<ValueType> swappedArgs(args.b(), args.a(), args.result(),
            args.bIsActive(), args.aIsActive());
        op(swappedArgs);
        args.setResultIsActive(swappedArgs.resultIsActive()); // forward the result of the active state
    }
```
-----------------------------

Some more details. `combineExtended` is designed to work on Trees of the same `ValueType`. When it encounters child nodes on the source tree but tiles on destination tree it will modify the values on the source tree in-place and then steals that result into the destination tree. It does this to be as efficient as possible; `combine2Extended` on the other hand **must** create new nodes for the destination tree as it's designed to work with trees of different `ValueType`'s.  For `combineExtended` to process values on the source tree as if they were on the destination tree the arguments must be swapped, hence this  `SwappedCombineOp`. Below is where this code is invoked:

https://github.com/AcademySoftwareFoundation/openvdb/blob/a71f65ca26664719d41bd282683ad3d3be1be68d/openvdb/openvdb/tree/RootNode.h#L3228-L3239

Hope this helps clear things up! I will propose this fix asap.

**Comment by frapit** [comment]
Thank you for the very detailed explanation and the proposed fix. I was not aware of this swap mechanism. I tested the fix and it works as intended!
