### ISSUE TITLE
[BUILD] In file included from /usr/local/include/tbb/parallel_reduce.herror:: 17: reference to 'split' is ambiguous

### ISSUE THREAD

**Issue by ArchakGoel** [AcademySoftwareFoundation/openvdb#1140]
### Environment
**Operating System:** MacOS Big Sur, version 11.4
**Version / Commit SHA:**openvdb v-5.20 
**CMake Version:** 3.21.1
**Compiler:** Apple clang version 12.0.5 (clang-1205.0.22.11) as obtained from 
`clang --version` on terminal

### Describe the problem
I am getting this error: In file included from _/usr/local/include/tbb/parallel_reduce.herror:: 17: reference to 'split' is ambiguous
when I try to build openVDB from sources_. Its reported on console in multiple places, wherever TBB dependency comes into the picture, during the build process.  I reported this on Intel TBB forums at this detailed[ post](community.intel.com/t5/Intel-oneAPI-Threading-Building/C-compilation-error-on-MacOS-In-file-included-from-usr-local/m-p/1302737#M14901).

I was told in a [reply](community.intel.com/t5/Intel-oneAPI-Threading-Building/C-compilation-error-on-MacOS-In-file-included-from-usr-local/m-p/1303289#M14905) by Intel tech team on the forum post that there are no available oneAPI solutions compatible with Mac OS 11.4. So it looks like I have no option but to shift my Mac OS back to an older version which is risky and is too much overhead.

### Question:
What version of openVDB I should install on my MacOS 11.4 without causing any compatibility issues?
### To Reproduce

1. Install all dependencies in a folder under home/.cmake/folderA
2. Run the attached shell scripts in the intel forum post I have mentioned above. Those scripts automatically provide dependency information to openVDB build process via CMAKE, builds and installs it.
3. See error when you build and run `make install`

###Other info:
I have also tried to install openVDB using `brew`, it installs but I get exactly same errors when I try to build my C++ application that uses the openVDB installation.

**Comment by Idclip** [comment]
Hi @ArchakGoel,

VDB 5.2.0 is pretty old and won't support TBB 2021/oneAPI. We've only very recently added support for TBB 2021 and it's not yet part of an official release (see the changelogs). You should be able to build against TBB 2021 with the latest master branch

**Comment by Idclip** [comment]
Closing, please reopen if you still have questions!
