### ISSUE TITLE
[Question] Is it possible to return progress info from openvdb?

### ISSUE THREAD

**Issue by CapLek** [AcademySoftwareFoundation/openvdb#1142]
Is it possible to return information about progress from openvdb long running tasks such as grid resampling, offsetting etc.?

**Comment by Idclip** [comment]
Hey @CapLek,

Good question, short answer is no - there is some support for runtime logging if you build with the Log4cplus dependency, but it's pretty limited and we don't tend to use it much. It would be nice if it was used more consistently or if we incorporated something more lightweight that can be used in these long running threaded ops (like spdlog).

**Comment by Idclip** [comment]
Going to migrate this to github discussions as it would be worth discussion this more.
