### ISSUE TITLE
Please check the example provided for Houdini, some are not set properlly 

### ISSUE THREAD

**Issue by vinyvince** [AcademySoftwareFoundation/openvdb#1155]
### Environment
**Operating System:** (e.g. Windows 2019, macOS-10.15, Linux CentOS 7.4)
**Version / Commit SHA:** (e.g VDB 7.2, SHA: 1a2b3c4d5e...)
**Other:** (e.g compiler, C++ standard etc.)

### Describe the bug
(A clear and concise description of what the bug is.)

### To Reproduce
1. Build with '...'
2. Run function '....'
3. See error

### Expected behavior
(A clear and concise description of what you expected to happen.)

### Additional context
(Add any other context about the problem here.)

**Comment by apradhana** [comment]
@vinyvince: Are you referring to the example provided for Houdini that is uploaded here: https://www.openvdb.org/download/?

**Comment by Idclip** [comment]
Closing due to lack of information, please re-open with more details if this is still a problem!
