### ISSUE TITLE
[BUILD] can’t find tbb 

### ISSUE THREAD

**Issue by StomatoGod** [AcademySoftwareFoundation/openvdb#1161]
Windows 10 
OpenVDB 8.1.1
CMake 3.21.1
msvc 2019

I was following the install directions and I am stuck at the toolchain part in command prompt:
 
 
`C:\PROGRA~1\CMake\bin\cmake.exe -DCMAKE_TOOLCHAIN_FILE=<C:\Dev\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 ..`

which returns an error at the end:

`-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TBB (missing: Tbb_INCLUDE_DIR Tbb_LIB_COMPONENTS tbb)
  (Required is at least version "2018.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTBB.cmake:335 (find_package_handle_standard_args)
  openvdb/openvdb/CMakeLists.txt:125 (find_package)
-- Configuring incomplete, errors occurred!
See also "C:/Dev/openvdb-master/build/CMakeFiles/CMakeOutput.log".`

Why isnt tbb being discovered correctly?

**Comment by Idclip** [comment]
What version of TBB have you installed?

**Comment by SimonNgj** [comment]
C:\PROGRA~1\CMake\bin\cmake.exe -DCMAKE_TOOLCHAIN_FILE=C:\Dev\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -A x64 ..
