### ISSUE TITLE
[BUILD] VDB AX SOP not included in build with other SOPs by default when building AX

### ISSUE THREAD

**Issue by richhones** [AcademySoftwareFoundation/openvdb#1175]
When building both OpenVDB AX and the OpenVDB Houdini Plugin (without specifying any custom dso list), it no longer automatically builds the OpenVDB AX SOP. Instead, in order to build the OpenVDB AX plugin you need to specify both OPENVDB_BUILD_HOUDINI_PLUGIN=ON and OPENVDB_BUILD_SOP_OpenVDB_AX=ON. 

This may be intentional but highlighting it is a change in functionality of the build system to how it used to work for building the OpenVDB AX SOP.

**Comment by danrbailey** [comment]
Hi @richhones - I agree that I would have thought the latter flag would not be required (ie OPENVDB_BUILD_HOUDINI_PLUGIN =ON and OPENVDB_BUILD_AX=ON would build the AX SOP?), but I'm a bit confused by all the AX options.

It is no doubt this PR that has changed the behaviour, see the discussion between @Idclip and myself (https://github.com/AcademySoftwareFoundation/openvdb/pull/1087#issuecomment-869641362). Would one of you be able to propose / submit a change to address this?

**Comment by richhones** [comment]
Ok @danrbailey thanks for verifying this wasnt intended behaviour. Have submitted a PR to fix this now.
