### ISSUE TITLE
[BUILD] Issue finding NumPy with several Python installed.

### ISSUE THREAD

**Issue by waebbl** [AcademySoftwareFoundation/openvdb#1226]
### Environment
**Operating System:** Gentoo Linux 2.8
**Version / Commit SHA:** openvdb-8.0.1
**CMake Version:** 3.21.3
**Compiler:** gcc-11.2.0

### Describe the problem
When configuring the package with several python interpreters installed (e.g. 3.{9,10}), it fails to find a proper python / numpy combination. I have python 3.9 and 3.10 installed and numpy 1.21.3 with python 3.9 support, i.e. numpy is only installed in the python 3.9's site-packages but not in the python 3.10 site-packages. I'm passing `-DPython_EXECUTABLE=/usr/bin/python3.9` to cmake, but it will find the latest 3.10 version and won't find any numpy for it.

The cmake docs tell: ["To ensure consistent versions between components Interpreter, Compiler, Development (or one of its sub-components) and NumPy, specify all components at the same time"](https://cmake.org/cmake/help/v3.21/module/FindPython.html). The code used in `openvdb/openvdb/python/CMakeLists` to look for numpy only passes the NumPy components. Additionally adding the `${OPENVDB_PYTHON_REQUIRED_COMPONENTS}` to the find_package call for numpy helps resolve this.

### To Reproduce
1. Pull the 8.0.1 tarball
2. Run CMake 
```cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCHOST=x86_64-pc-linux-gnu -DCMAKE_INSTALL_DOCDIR=share/doc/openvdb-8.0.1-r1/ -DOPENVDB_ABI_VERSION_NUMBER=8 -DOPENVDB_BUILD_DOCS=yes -DOPENVDB_BUILD_UNITTESTS=no -DOPENVDB_BUILD_VDB_LOD=no -DOPENVDB_BUILD_VDB_RENDER=no -DOPENVDB_BUILD_VDB_VIEW=no -DOPENVDB_CORE_SHARED=ON -DOPENVDB_CORE_STATIC=no -DOPENVDB_ENABLE_RPATH=OFF -DUSE_CCACHE=OFF -DUSE_COLORED_OUTPUT=ON -DUSE_EXR=ON -DUSE_LOG4CPLUS=ON -DOPENVDB_BUILD_PYTHON_MODULE=ON -DUSE_NUMPY=yes -DPYOPENVDB_INSTALL_DIRECTORY=/usr/lib/python3.9/site-packages -DPython_EXECUTABLE=/usr/bin/python3.9 -DOPENVDB_SIMD=AVX -DCMAKE_BUILD_TYPE=Gentoo /var/tmp/portage/media-gfx/openvdb-8.0.1-r1/work/openvdb-8.0.1```
3. Build with: fails at configuration step, no building is done
```-- Found Python: /usr/include/python3.10) (found suitable version "3.10.0", minimum required is "2.7")
CMake Error at openvdb/openvdb/python/CMakeLists.txt:99 (message):
  Could NOT find NumPy (Required is at least version "1.14.0")


-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/media-gfx/openvdb-8.0.1-r1/work/openvdb-8.0.1_build/CMakeFiles/CMakeOutput.log".
See also "/var/tmp/portage/media-gfx/openvdb-8.0.1-r1/work/openvdb-8.0.1_build/CMakeFiles/CMakeError.log".
```

### Additional context
- We use an additional inital cache and a custom toolchain file on Gentoo, which I removed from the above cmake line. They should however not infer with the issue and are used for thousands of packages in Gentoo.
- Additionally I have to pass the `-DPython_INCLUDE_DIR` artifact in addition to the `-DPython_EXECUTABLE` to actually make the patch work, but this might the Gentoo specific.
- https://bugs.gentoo.org/788886
- https://github.com/gentoo/gentoo/pull/22738

**Comment by Idclip** [comment]
@waebbl thanks a lot for the feedback and patch! We've actually just bumped our minimum CMake to 3.15 on master so a lot of this branching has been removed. I've opened a PR which incorporates this change.

**Comment by waebbl** [comment]
@Idclip thanks for your quick action.
