### ISSUE TITLE
[BUG] blosc is discovered incorrectly - its dependencies are added to OpenVDB dependencies

### ISSUE THREAD

**Issue by yurivict** [AcademySoftwareFoundation/openvdb#1250]
### Environment
**Operating System:** FreeBSD 13
**Version / Commit SHA:** 9.0.0
**Other:** clang-12

### Describe the bug
```cmake/FindBlosc.cmake``` is used to discover ```c-blosc```. It automatically adds libicui18n.so, libzstd.so, libsnappy.so to dependencies when this isn't needed.

Instead ```pkg-config``` should be used:
```
$ pkg-config --libs blosc
-L/usr/local/lib -lblosc 
```

c-blosc dependencies:
```
$ pkg info -d c-blosc
c-blosc-1.21.0:
	zstd-1.5.0
	snappy-1.1.9_1
	liblz4-1.9.3,1
```
```

**Comment by Idclip** [comment]
`FindBlosc.cmake` only adds `zstd`, `snappy`, `zlib` and `lz4` when `BLOSC_USE_EXTERNAL_SOURCES` is `ON` - and if that variable is `ON` they are required. I don't know what `libicui18n` is...

**Comment by Idclip** [comment]
@yurivict can you provide more information? From what I can see this doesn't look like a problem with VDB.

**Comment by Idclip** [comment]
Closing this, please provide more information if this is still an issue.
