### ISSUE TITLE
How to render in openvdb

### ISSUE THREAD

**Issue by hjhj111** [AcademySoftwareFoundation/openvdb#1278]
How to render a model in openvdb? Does it offer this application or I need to render  with opengl or others? Thank you.

**Comment by Idclip** [comment]
Hi @hjhj111, VDB comes with command line binary tools `vdb_render` and `vdb_view`. `vdb_render` provides some basic options for rendering .vdb files. `vdb_view` is a basic OpenGL viewer for .vdb files. If you need anything more advanced there are a number of DCCs which support VDBs (Houdini/Maya/Blender etc).

**Comment by SimonNgj** [comment]
Hi, where do I find the command line vdb_view and vdb_render. I followed the instruction to build OpenVDB on Windows, but could find vdb_view and vdb_render, I only sww vdb_print.exe

**Comment by SimonNgj** [comment]
lol. I checked the CMakeLists.txt file and found that:
option(OPENVDB_BUILD_VDB_PRINT "Build vdb_print" ON)
option(OPENVDB_BUILD_VDB_LOD "Build vdb_lod" OFF)
option(OPENVDB_BUILD_VDB_RENDER "Build vdb_render" OFF)
option(OPENVDB_BUILD_VDB_VIEW "Build vdb_view" OFF)
I guess I should turn them on
