### ISSUE TITLE
[BUILD] openvdb/openvdb/python/CMakeFiles/pyopenvdb.dir/build.make:173: target pattern contains no `%'. Stop.

### ISSUE THREAD

**Issue by andabi** [AcademySoftwareFoundation/openvdb#1281]
### Environment
**Operating System: Ubuntu 20.04
**Version / Commit SHA: VDB 9.0
**CMake Version: 3.16.3
**Compiler: gcc 9.3.0

### Describe the problem
I got this error during `cmake -D OPENVDB_BUILD_PYTHON_MODULE=ON` and `make -j4` to use python module.

`openvdb/openvdb/python/CMakeFiles/pyopenvdb.dir/build.make:173: target pattern contains no '%'. Stop.`

A message snippet during cmake:
`
-- ----------------------------------------------------
-- ------------ Configuring OpenVDBPython -------------
-- ----------------------------------------------------
-- Found Python: /home/dabi/miniconda3/include/python3.9) (found suitable version "3.9", minimum required is "2.7")
-- Found non-suffixed boost_python, assuming to be python version "3.9" compatible
-- ----------------------------------------------------
`

### To Reproduce
1. Checkout repo
`mkdir build; cd build`

2. Run CMake
`cmake -D OPENVDB_BUILD_PYTHON_MODULE=ON ..`

3. Build with 
`make -j4`

`openvdb/openvdb/python/CMakeFiles/pyopenvdb.dir/build.make:173: target pattern contains no `%'. Stop.`

### Additional context
`boost-python` had been properly installed.
Python version is 3.9.

**Comment by Idclip** [comment]
Hi @andabi - I'm currently investigating this in #1353. I have some things you can try to work around this there.

**Comment by Idclip** [comment]
This should now be fixed. If you encouter issues with finding boost_python or boost_numpy try providing `-D Boost_PYTHON_VERSION=X` or `-D Boost_PYTHON_VERSION_MAJOR=X.Y` to tell CMake exactly which version of boost python/numpy you're expecting.
