### ISSUE TITLE
Can a grid of levelset contain serveral values not only a value of signed distance?

### ISSUE THREAD

**Issue by hjhj111** [AcademySoftwareFoundation/openvdb#1288]
Can a grid of levelset contain serveral values not only a value of signed distance? or I should define a struct that contains serveral values?

**Comment by apradhana** [comment]
No, a level set is implemented as a Float Grid with [GridClass](https://www.openvdb.org/documentation/doxygen/namespaceopenvdb_1_1v8__0.html#a511a7f5bd868162ec06bcc20b98e160e) set to be GRID_LEVEL_SET. You can see further explanation [here](https://www.openvdb.org/documentation/doxygen/overview.html#secGrid).
