### ISSUE TITLE
[static analyzer warning]

### ISSUE THREAD

**Issue by andreys7** [AcademySoftwareFoundation/openvdb#1299]
### Environment
**Operating System:** (--)
**Version / Commit SHA:** --)
**CMake Version:** (--)
**Compiler:** (--)

### Describe the problem
Static analyzer complains:
 
openvdb/math/Math.h line 520, col 26: absolute value function 'labs' given an argument of type 'long long' but has parameter of type 'long' which may cause truncation of value 
      note: use function 'std::abs' instead

Line:     int64_t difference = labs(longLeft - longRight); 

Is it bug or trick?

### To Reproduce
1. Checkout repo '...'
2. Run CMake '....'
3. Build with '....'

### Additional context
(Add any other context about the problem here.)

**Comment by Idclip** [comment]
Hey @andreys7 thanks - was this on Windows by any chance?

**Comment by andreys7** [comment]
Yes, it was in Windows, Visual Studio 2019
