### ISSUE TITLE
CSGUnion() throws access violation in debug build with released linked OpenVDB

### ISSUE THREAD

**Issue by 3Descape** [AcademySoftwareFoundation/openvdb#1314]
### Environment
**Operating System:** Windows 10 Pro
**Version / Commit SHA:** 895efbfe0d84b30dbf44b3d7e11e68e298d1ba3c(aka. current master)
**Other:** MSVC 2019 x64 .dll release built

### Error
- Debug built of project with relase built of openvdb linked: When joining multiple FloatGrids with openvdb::tools::csgUnion() the release build of the dynamically linked openvdb library throws an "access violation reading location 0xFFFFFFFFFFFFFFFF" error. 
- Debug with debug lib works.
- Release with release lib works. 

### Steps To Reproduce
Link dynamic release library with debug build and execute a openvdb::tools::csgUnion() operation.

### Expected behavior
It should be possible to link a release version of the library with a debug build without any errors.

### Additional context
Debug build with release library linked output: An access violation error occured. 
![bug_release](https://user-images.githubusercontent.com/5028761/155702250-6becb913-e557-420a-b723-901cc262cfef.jpg)
Debug build with debug library linked output: No error occured.
![bug_debug](https://user-images.githubusercontent.com/5028761/155702278-9578fa42-12f8-46b0-87e9-938851ee865a.jpg)

**Comment by Idclip** [comment]
> It should be possible to link a release version of the library with a debug build without any errors.

Eh... on Windows yes and no - you'll need to make sure you're using the same CRT throughout all your libraries. This can be a pain to set up. The release build of OpenVDB will use the release version of the Windows CRT. If you're using a VS project, debug builds will typically force linkage to the debug version of the CRT (usually with `/MDd` or `/MTd`). This will not be compatible with the default release installation of OpenVDB or any other release library that has an STL interface. 

If this is indeed the case and you just want debug info in your program and want to continue using release dependencies, I suggest you configure your project to use the release version of the CRT (i.e. `/MD` or `/MT`) with debug information (i.e. `-g`).

**Comment by 3Descape** [comment]
Okay, thank you for clarifiying that ;)

Another (related) question in this case: Should the FindOpenVDB.cmake script provide debug/release dependent library linking based on the build type like other libraries do? From what I've seen I think currently not, right?
I think form a usability perspective it would penefit the library. Just in case I might feel like trying to address this, would there even be an interest from your side to add that to the offical repo or is there no priority to support/maintain out of the box debug library linking in the long run?

Thank you very much for your time and have a nice weekend ;)
