### ISSUE TITLE
'signedFloodFill' is not a member of 'openvdb::v9_0::tools'

### ISSUE THREAD

**Issue by SimonNgj** [AcademySoftwareFoundation/openvdb#1345]
When running example "Creating and writing a grid", I faced this error: 'signedFloodFill' is not a member of 'openvdb::v9_0::tools'.
Anyone know hot to solve?

**Comment by Idclip** [comment]
Make sure you're inlcuding the right header files. Without any example code that's the best possible advice I can provide.

**Comment by SimonNgj** [comment]
Thanks, I found that I need to add: 
#include <openvdb/tools/SignedFloodFill.h>
