### ISSUE TITLE
CSG Boolean operations do not work with *.vdb created from point cloud

### ISSUE THREAD

**Issue by SimonNgj** [AcademySoftwareFoundation/openvdb#1354]
I'm trying this example from the cookbook:
```
#include <openvdb/openvdb.h>
#include <openvdb/tools/LevelSetSphere.h>
#include <openvdb/tools/Composite.h>

int main()
{
    openvdb::initialize();

    // Two grids of the same type containing level set volumes
    openvdb::FloatGrid::Ptr gridA = openvdb::tools::createLevelSetSphere<openvdb::FloatGrid>( 200.0, openvdb::Vec3f(0., 0., 0.), 4., 8.0);
    openvdb::FloatGrid::Ptr gridB = openvdb::tools::createLevelSetSphere<openvdb::FloatGrid>( 300.0, openvdb::Vec3f(150., -190., 0.), 4., 8.0);

    openvdb::io::File("gridA.vdb").write({ gridA });
    openvdb::io::File("gridB.vdb").write({ gridB });

    openvdb::FloatGrid::ConstPtr
        copyOfGridA = gridA->deepCopy(),
        copyOfGridB = gridB->deepCopy();

    openvdb::tools::csgUnion(*gridA, *gridB);

    gridA->setName("LevelSetSphere");

    openvdb::io::File("grid_result.vdb").write({ gridA });
}
```
I works fine. However, when I try with grid created from points:
```
#include <iostream>
#include <vector>
#include <openvdb/openvdb.h>
#include <openvdb/tools/LevelSetSphere.h>
#include <openvdb/tools/Composite.h>
#include <openvdb/points/PointConversion.h>
#include <openvdb/points/PointCount.h>
#include "openvdb/tools/GridTransformer.h"
#include "openvdb/tools/Interpolation.h"
#include "openvdb/util/Util.h"

using namespace openvdb;

int main()
{
    openvdb::initialize();

    // Create a vector with point positions.
    std::vector<openvdb::Vec3R> positions;
    positions.push_back(openvdb::Vec3R(0, 1, 0));
    positions.push_back(openvdb::Vec3R(1.5, 3.5, 1));
    positions.push_back(openvdb::Vec3R(-1, 3, -2));
    positions.push_back(openvdb::Vec3R(1.1, 1.25, 0.6));
    positions.push_back(openvdb::Vec3R(5, 1, 2));
    positions.push_back(openvdb::Vec3R(5, -3.5, 2));
    positions.push_back(openvdb::Vec3R(-2, 5, -2));
    positions.push_back(openvdb::Vec3R(2, 2.5, 1));

    openvdb::points::PointAttributeVector<openvdb::Vec3R> positionsWrapper(positions);
    float voxelSize = 0.5;

    openvdb::math::Transform::Ptr transform = openvdb::math::Transform::createLinearTransform(voxelSize);

    openvdb::points::PointDataGrid::Ptr grid =
        openvdb::points::createPointDataGrid<openvdb::points::NullCodec,
        openvdb::points::PointDataGrid>(positions, *transform);
    // Set the name of the grid
    grid->setName("Points");
    openvdb::io::File("pA.vdb").write({ grid });

    openvdb::io::File file("pA.vdb");
    file.open();

    GridBase::Ptr baseGrid;
    for (openvdb::io::File::NameIterator nameIter = file.beginName();
        nameIter != file.endName(); ++nameIter) {
        baseGrid = file.readGrid(nameIter.gridName());
    }

    file.close();

    FloatGrid::Ptr gridA = gridPtrCast<FloatGrid>(baseGrid);
    FloatGrid::Ptr gridB = gridA->deepCopy();
    gridB->transform().postRotate(M_PI / 4.0f, math::Y_AXIS);
    tools::resampleToMatch<tools::BoxSampler>(*gridA, *gridB);
    
    FloatGrid::Ptr result = gridA->deepCopy();
    FloatGrid::Ptr gridB2 = gridB->deepCopy();
    
    tools::csgUnion(*result, *gridB);
    openvdb::io::File("pA_result.vdb").write({ result });
    
    return 0;
}
```
I get the exception thrown error, anyone has any idea to solve?
![image](https://user-images.githubusercontent.com/22513384/162666036-6f6c2eb3-22b9-49ab-97da-6ecf0eece96e.png)

**Comment by SimonNgj** [comment]
Exception thrown happens at: FloatGrid::Ptr gridB = gridA->deepCopy();
But even when I changed the code to: 
FloatGrid::Ptr gridA = gridPtrCast<FloatGrid>(baseGrid);
FloatGrid::Ptr gridB = gridPtrCast<FloatGrid>(baseGrid);
Exception thrown will happen at: 
gridB->transform().postRotate(M_PI / 4.0f, math::Y_AXIS);

**Comment by SimonNgj** [comment]
Is there any way to convert a PointDataGrid to a FloatGrid?

**Comment by Idclip** [comment]
> Is there any way to convert a PointDataGrid to a FloatGrid?

`PointDataGrid`'s and `FloatGrid`'s are difference distinct classes in OpenVDB that hold fundamentally different data, so you can't simply assign or cast one to the other - doing so will result in error like you're experiencing. In other words, this:

```
FloatGrid::Ptr gridA = gridPtrCast<FloatGrid>(baseGrid);
```

will cause `gridA` to be a `nullptr` if `baseGrid` is not a `FloatGrid`.


What are you conceptually trying to do here? `PointDataGrid`'s do not automatically represent implicit fields. `tools::csg` operations only work on valid floating point OpenVDB level sets. Consider looking at `tools/ParticlesToLevelSet.h` which works on point positions directly and allows you to re-construct an implicit surface `FloatGrid` from point positions.

The only tools that exist to convert `PointDataGrid`'s to valid surfaces are in `points/PointRasterizeSDF.h`, but these are still experimental and have only just been merged.

**Comment by Idclip** [comment]
Ah, in which case you don't need `FloatGrid` representations for this at all, you can simply convert your points to `BoolGrid`s or, better, `MaskGrid`s using topology copies. Take a look at the tools in `points/PointMask.h` which demonstrate this. Then, to perform acitvity intersection, you can use the Grid/Tree member methods `grid->topologyIntersection`

**Comment by SimonNgj** [comment]
I solved this problem
