### ISSUE TITLE
Volume to mesh

### ISSUE THREAD

**Issue by SimonNgj** [AcademySoftwareFoundation/openvdb#1387]
I am converting a point cloud to level set and then rasterizing it and converting volume to mesh. I want the mesh to be triangular mesh, but the output only has quads and no triangles at all. I attach one snapshot from my result below. Anyone know how to get triangles, instead of quads
![Capture](https://user-images.githubusercontent.com/22513384/169722454-67df1b49-bdbf-4980-8abc-b8da082ea2a5.PNG)
?
![Capture2](https://user-images.githubusercontent.com/22513384/169722487-5fdd0aaa-f711-4de5-bfb4-6d670ea20093.PNG)

**Comment by Idclip** [comment]
Hi @SimonNgj, the VolumeToMesh algorithms only output quads. The triangle list output vector in the adpativity signature is only populated with triangles which hit the adaptivity threshhold. In your case the treshhold is 0, so the list will be empty. 

Note though that you shouldn't increase this threshhold just to get triangles. The adaptivity control allows for the generated mesh ploygons to vary in size so it will produce a fundamentally different mesh with different threshholds. If you just want triangles you will have to loop through the quad index list and rebuild your own triangle index list or feed it to an external tool to do so.

I realise that the documentation on this function is confusing, we'll update it!
