### ISSUE TITLE
How to build pyopenvdb for a specific python version?

### ISSUE THREAD

**Issue by francescofugazzi** [AcademySoftwareFoundation/openvdb#1407]
I followed a guide for compiling pyopenvdb but it automatically built it binded to Python 3.10.
I need it to run on 3.9 environment. How can i force it to build for 3.9?

**Comment by francescofugazzi** [comment]
thanks for the reply. I'm trying to build with numpy but then cmake gives me this errors:

```
-- Could NOT find Boost (missing: python39) (found suitable version "1.79.0", minimum required is "1.70")
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: python) (found suitable version "1.79.0",
  minimum required is "1.70")
```

**Comment by francescofugazzi** [comment]
I finally managed to compile it. I restarted from scratch a couple times. If I install boost-python from vcpkg it only considers the Python 3.10 that it installs and ignores the Python_ROOT_DIR.
There was a time I managed to compile it with 3.10 and I also recompiled the app I was using to call pyopenvdb but then wasn't working because of lack of numpy and trying to add it was always failing. But anyway i was able to import pyopenvdb and use os.import for loading the two folders contining the dlls
Right now I managed to compile everything with python 3.9 and numpy, after i installed boost through pip in my conda environment, as I first intended but now when loading the dlls path it sayd it can't find all the libraries... i'm really a newbie and i don't know anymore where to look for get it working

**Comment by francescofugazzi** [comment]
right now the test i'm doing directly in the installed folder as misteriously it's not loading it through system variable as before

By launching Python then i do:
```
import os
os.add_dll_directory("C:\\Program Files\\OpenVDB\\bin\\")
os.add_dll_directory("E:\\instant-ngp\\vcpkg\\installed\\x64-windows\\bin\\")
import pyopenvdb
```

but then this is the result and with the previos 3.10 attempt without numpy was loading
`os.add_dll_directory("E:\\instant-ngp\\vcpkg\\installed\\x64-windows\\bin\\")`

**Comment by Idclip** [comment]
@francescofugazzi did you manage to resolve this? My only other suggestion is to point you to this older thread where I was previously testing a similar setup:

https://github.com/AcademySoftwareFoundation/openvdb/issues/946#issuecomment-775953390

**Comment by francescofugazzi** [comment]
Hi

a few days back I managed to compile it :)
I avoided installing the boost libraries and python package from VCPKG
I compiled the boost libraries manually (also the dlls) and I changed the paths in cmakecache.txt for the required components and finally it worked! I was so happy and in this way i compiled for python 3.9 instead of 3.10 and with numpy support.
About importing the dlls I did it manually by copying the openvdb.dll and the boost dlls in the path where i needed to run the script and everything worked flawlessy

**Comment by Idclip** [comment]
Great to hear @francescofugazzi, I will close this!
