### ISSUE TITLE
Convert points attribute to volume

### ISSUE THREAD

**Issue by gearslogy** [AcademySoftwareFoundation/openvdb#143]
Hi, I have a problem that how can i convert points or particles attributes to a scalar/vector fields.

In Houdini have a sop node:vdb from particles,that can convert the attribute to a volume.

I can convert the particles to volume/sdf(density grid) that used the  "MyParticleList" , but how can extract the "v" vector attribute to a openvdb::Vec3s grid(velocity grid) and other typed attribute to their typed grid

thanks.

**Comment by Idclip** [comment]
There's a number of ways you can achieve this. With generic point lists you can use `openvdb::tools::ParticlesToLevelSet` whose second template parameter can be a custom type of an additional attribute to rasterize:

https://github.com/AcademySoftwareFoundation/openvdb/blob/2561c253d052aa27c5405d7fef4fcec1b2923ba0/openvdb/openvdb/tools/ParticlesToLevelSet.h#L156-L159

See the `testRasterizeSpheresAndId` test as an example which additionally rasterizes an `int32_t` id attribute:

https://github.com/AcademySoftwareFoundation/openvdb/blob/2561c253d052aa27c5405d7fef4fcec1b2923ba0/openvdb/openvdb/unittest/TestParticlesToLevelSet.cc#L297


Alternatively, if you're using OpenVDB Points, you can use the new tools available in `points/PointsRasterizeSDF.h`:

https://github.com/AcademySoftwareFoundation/openvdb/blob/2561c253d052aa27c5405d7fef4fcec1b2923ba0/openvdb/openvdb/points/PointRasterizeSDF.h#L138-L150

A quickly typed example:

```
using TypesToTransfer = openvdb::TypeList<Vec3f>; // A single vec3f attribue

auto grids = 
    rasterizeSpheres<decltype(pointDataGrid), TypesToTransfer>
          (pointDataGrid, /*radius=*/1.0,  /*attributes=*/{ "v" });

openvdb::FloatGrid::Ptr surface = openvdb::StaticPtrCast<FloatGrid>(grids[0]);
openvdb::Vec3fGrid::Ptr vel = openvdb::StaticPtrCast<Vec3fGrid>(grids[1]);
```
