### ISSUE TITLE
Issues including PNanoVDB.h in vulkan GLSL compute shader via glslc 

### ISSUE THREAD

**Issue by trsh** [AcademySoftwareFoundation/openvdb#1476]
### Environment
**Operating System:** (e.g. Windows 11 x64)
**Version / Commit SHA:** (master)
**Other:** (glslc to spirv)

### Describe the bug
```
PNanoVDB.comp:179: error: 'pnanovdb_buf_data' : undeclared identifier
PNanoVDB.comp:179: error: 'pnanovdb_buf_data' :  left of '[' is not of type array, matrix, or vector
PNanoVDB.comp:179: error: 'return' : type does not match, or is not convertible to, the function's return type
3 errors generated.
```
### To Reproduce

glslc.exe my_shader2.comp

where my_shader2.comp

```glsl
#version 430

#include "PNanoVDB.comp"

precision highp float;
precision highp int;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main() {
    uvec3 invocation_id = gl_GlobalInvocationID;
    return;
}

```
### Expected behavior
Flawless compile

### Additional context
No

**Comment by trsh** [comment]
Tried to replace the line with 

`return buf[(byte_offset >> 2u)];` , but got

```
PNanoVDB.comp:179: error: 'buf' :  left of '[' is not of type array, matrix, or vector
PNanoVDB.comp:179: error: 'return' : type does not match, or is not convertible to, the function's return type
2 errors generated.
```

**Comment by trsh** [comment]
Never mind. Got it

**Comment by wilkesreid** [comment]
@trsh How did you get it working?

**Comment by trsh** [comment]
So I see folks landing on this issue from google orsmth, so I will provide the solution:

`pnanovdb_buf_data` is a uint buffer that holds the grid and you have to provide your self.

Something like: 

```glsl
layout(set = 0, binding = 0) buffer grid_buffer
{
       uint pnanovdb_buf_data[];
};
```

Mark, I did switch to HLSL, so this example above might be incorrect and require need some tuning. But its the right direction to go. Just check `PNanoVDB.h` for leads.

**Comment by endriau** [comment]
@trsh thanks for this mate. I was having the same issue, got it working :)
