### ISSUE TITLE
[BUILD] undefined reference to `memcpy@GLIBC_2.14' error when building openvdb.cc.o

### ISSUE THREAD

**Issue by panchyni** [AcademySoftwareFoundation/openvdb#1495]
### Environment
**Operating System:** CentOS Linux release 7.9.2009 (Core)
**Version / Commit SHA:** VDB 9.1.1, commit 4ffb9bcdf3488fa8aa60ba3f1cf393f140c32056
**CMake Version:** 3.24.2
**Compiler:** g++ (conda-forge gcc 12.1.0-17) 12.1.0

### Describe the problem
After cloning the repository and installing the dependencies in a conda environment, I ran 'cmake' as described in the README (which ran fine) and then 'make -j4', which gave the following error:

[ 94%] Building CXX object openvdb/openvdb/CMakeFiles/openvdb_static.dir/openvdb.cc.o
/mnt/ufs18/home-205/panchyni/anaconda3/envs/openvdb_dep/bin/../lib/gcc/x86_64-conda-linux-gnu/12.1.0/../../../../x86_64-conda-linux-gnu/bin/ld: /usr/lib64/libz.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: error: ld returned 1 exit status
make[2]: *** [openvdb_cmd/vdb_print/vdb_print] Error 1
make[1]: *** [openvdb_cmd/vdb_print/CMakeFiles/vdb_print.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

### To Reproduce
1. Clone the repo with https://github.com/AcademySoftwareFoundation/openvdb.git
2. Install dependencies in a conda environment (see below)
3. Follow the install instructions on the README:
   cd openvdb
   mkdir build
   cd build
   cmake ..
   make -j

### Additional context
I am working on a university computing cluster without root access, so I am using conda to
handle dependencies as recommended. Below the conda environment I am using for the make process:

# packages in environment at /mnt/home/panchyni/anaconda3/envs/openvdb_dep:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
binutils_impl_linux-64    2.39                 h6ceecb4_0    conda-forge
blosc                     1.21.1               h83bc5f7_3    conda-forge
boost                     1.80.0          py310hc4a4660_1    conda-forge
boost-cpp                 1.80.0               h75c5d50_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cmake                     3.24.2               h5432695_0    conda-forge
expat                     2.4.9                h27087fc_0    conda-forge
gcc                       12.1.0              h9ea6d83_10    conda-forge
gcc_impl_linux-64         12.1.0              hea43390_17    conda-forge
gxx                       12.1.0              h9ea6d83_10    conda-forge
gxx_impl_linux-64         12.1.0              hea43390_17    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcurl                   7.85.0               h2283fc2_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-devel_linux-64     12.1.0              h1ec3361_17    conda-forge
libgcc-ng                 12.1.0              h8d9b700_17    conda-forge
libgfortran-ng            12.1.0              h69a702a_17    conda-forge
libgfortran5              12.1.0              hdcd56e2_17    conda-forge
libgomp                   12.1.0              h8d9b700_17    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnghttp2                1.47.0               hff17c54_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libsanitizer              12.1.0              ha89aaad_17    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-devel_linux-64  12.1.0              h1ec3361_17    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_17    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.44.2               h166bdaf_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.23.3          py310h53a5b5f_0    conda-forge
openssl                   3.0.5                h166bdaf_2    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
python                    3.10.6          ha86cf86_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
rhash                     1.4.3                h166bdaf_0    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
snappy                    1.1.9                hbd366e4_1    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbb                       2021.6.0             h924138e_0    conda-forge
tbb-devel                 2021.6.0             h924138e_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge

You should me able to recreate this environment with:

conda create -n openvdb cmake gcc gxx bost tbb tbb-devel blosc=1.21.1

Please let me know if you require further information/files

**Comment by Idclip** [comment]
Looks like it's trying to using your systems installation of `zlib`, not the one from your conda environment? Try building with `-DZLIB_ROOT=/path/to/you/conda/zlib/root` and make sure you see the correct paths to `zlib` appear during cmake/make. You can also provide the locations to `zlib.h` and `libz` manually:

https://cmake.org/cmake/help/latest/module/FindZLIB.html

**Comment by panchyni** [comment]
That fixed it. I though I unloaded all the system varibles but I missed zlib on the dependency list and in the error. Thanks for you help, I appreciate it.
