### ISSUE TITLE
Bool LeafNode initialization behavior with designated on and off values

### ISSUE THREAD

**Issue by hozhaoea** [AcademySoftwareFoundation/openvdb#1520]
Hi!

I was trying to do a topology copy of a bool tree, with both active and inactive value initialized to `false` for the new tree. But the result has active voxels initialized to `true`, and active tiles set to `false`.

```openvdb::BoolTree* NewTree = new openvdb::BoolTree(OldGrid->tree(), /*inactiveValue*/ false, /*activeValue*/ false, openvdb::TopologyCopy());```

I traced to this line:
https://github.com/AcademySoftwareFoundation/openvdb/blob/be0e7a78861d2b7d9643f7a0cab04f3ab5951686/openvdb/openvdb/tree/LeafNodeBool.h#L847

Seems like the copy behavior for bool leaf node is to simply use the value mask when `offValue` is set to `false`? Is this intended behavior? Any suggested route I should take instead?

Thanks!

**Comment by kmuseth** [comment]
Thanks, this looks like a legit issue. I'll fix it in the near future

**Comment by Idclip** [comment]
Reopening until fixed!
