### ISSUE TITLE
[BUILD] openvdb_ax/codegen/Types.h:202:76: error: incomplete type 'openvdb::v10_0::ax::codegen::int_t<4>' used in nested name specifier

### ISSUE THREAD

**Issue by malaterre** [AcademySoftwareFoundation/openvdb#1526]
### Environment
**Operating System:** Linux Debian sid/i386
**Version / Commit SHA:** 10.0
**CMake Version:** 3.25
**Compiler:** gcc-12

### Describe the problem

```
[ 25%] Building CXX object openvdb_ax/openvdb_ax/CMakeFiles/openvdb_ax_shared.dir/codegen/Codecs.cc.o
cd /home/malat/openvdb/obj-i686-linux-gnu/openvdb_ax/openvdb_ax && /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_IOSTREAMS_DYN_LINK -DOPENVDB_AX_DLL -DOPENVDB_AX_PRIVATE -DOPENVDB_AX_REGENERATE_GRAMMAR -DOPENVDB_DLL -DOPENVDB_USE_DELAYED_LOADING -DOPENVDB_USE_LOG4CPLUS -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS="64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS" -Dopenvdb_ax_shared_EXPORTS -I/home/malat/openvdb/openvdb_ax/openvdb_ax/.. -I/home/malat/openvdb/openvdb_ax/openvdb_ax/../../openvdb_cmd/vdb_ax -I/home/malat/openvdb/obj-i686-linux-gnu/openvdb_ax/openvdb_ax/openvdb_ax/grammar -I/home/malat/openvdb/openvdb/openvdb/.. -I/home/malat/openvdb/obj-i686-linux-gnu/openvdb/openvdb -I/home/malat/openvdb/obj-i686-linux-gnu/openvdb/openvdb/openvdb -isystem /usr/lib/llvm-14/include -isystem /usr/include/Imath -g -O2 -ffile-prefix-map=/home/malat/openvdb=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,--no-keep-memory -Wl,--reduce-memory-overhead -g1 -fvisibility=hidden -fvisibility-inlines-hidden -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -std=c++17 -MD -MT openvdb_ax/openvdb_ax/CMakeFiles/openvdb_ax_shared.dir/codegen/Codecs.cc.o -MF CMakeFiles/openvdb_ax_shared.dir/codegen/Codecs.cc.o.d -o CMakeFiles/openvdb_ax_shared.dir/codegen/Codecs.cc.o -c /home/malat/openvdb/openvdb_ax/openvdb_ax/codegen/Codecs.cc
In file included from /home/malat/openvdb/openvdb_ax/openvdb_ax/../openvdb_ax/codegen/FunctionTypes.h:69,
                 from /home/malat/openvdb/openvdb_ax/openvdb_ax/codegen/Codecs.h:11,
                 from /home/malat/openvdb/openvdb_ax/openvdb_ax/codegen/Codecs.cc:6:
/home/malat/openvdb/openvdb_ax/openvdb_ax/../openvdb_ax/codegen/Types.h:202:76: error: incomplete type 'openvdb::v10_0::ax::codegen::int_t<4>' used in nested name specifier
  202 | template <> struct LLVMType<void*> : public LLVMType<int_t<sizeof(void*)>::type*> {};
      |                                                                            ^~~~
/home/malat/openvdb/openvdb_ax/openvdb_ax/../openvdb_ax/codegen/Types.h:202:81: error: template argument 1 is invalid
  202 | template <> struct LLVMType<void*> : public LLVMType<int_t<sizeof(void*)>::type*> {};
      |                                                                                 ^
make[2]: *** [openvdb_ax/openvdb_ax/CMakeFiles/openvdb_ax_shared.dir/build.make:146: openvdb_ax/openvdb_ax/CMakeFiles/openvdb_ax_shared.dir/codegen/Codecs.cc.o] Error 1
make[2]: Leaving directory '/home/malat/openvdb/obj-i686-linux-gnu'
make[1]: *** [CMakeFiles/Makefile2:572: openvdb_ax/openvdb_ax/CMakeFiles/openvdb_ax_shared.dir/all] Error 2
make[1]: Leaving directory '/home/malat/openvdb/obj-i686-linux-gnu'
make: *** [Makefile:149: all] Error 2
```

### To Reproduce
1. Checkout repo at tag 10.
2. Run CMake `cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/i386-linux-gnu -DBUILD_TEST:BOOL=ON -DCMAKE_SKIP_RPATH:BOOL=ON -DCONCURRENT_MALLOC:STRING=Tbbmalloc -DNANOVDB_BUILD_BENCHMARK:BOOL=ON -DNANOVDB_BUILD_EXAMPLES:BOOL=ON -DNANOVDB_BUILD_UNITTESTS:BOOL=ON -DNANOVDB_CUDA_KEEP_PTX:BOOL=OFF -DNANOVDB_USE_CUDA:BOOL=OFF -DNANOVDB_USE_INTRINSICS:BOOL=ON -DNANOVDB_USE_OPENVDB:BOOL=ON -DOPENVDB_AX_STATIC:BOOL=OFF -DOPENVDB_BUILD_AX:BOOL=ON -DOPENVDB_BUILD_AX_GRAMMAR:BOOL=ON -DOPENVDB_BUILD_AX_UNITTESTS:BOOL=ON -DOPENVDB_BUILD_DOCS:BOOL=OFF -DOPENVDB_BUILD_NANOVDB:BOOL=ON -DOPENVDB_BUILD_PYTHON_MODULE:BOOL=ON -DOPENVDB_BUILD_PYTHON_UNITTESTS:BOOL=ON -DOPENVDB_BUILD_UNITTESTS:BOOL=ON -DOPENVDB_BUILD_VDB_AX:BOOL=ON -DOPENVDB_BUILD_VDB_LOD:BOOL=ON -DOPENVDB_BUILD_VDB_RENDER:BOOL=ON -DOPENVDB_BUILD_VDB_TOOL:BOOL=ON -DOPENVDB_BUILD_VDB_VIEW:BOOL=ON -DOPENVDB_CORE_STATIC:BOOL=OFF -DOPENVDB_ENABLE_RPATH:BOOL=OFF -DOPENVDB_TOOL_USE_EXR:BOOL=ON -DOPENVDB_TOOL_USE_JPG:BOOL=ON -DOPENVDB_TOOL_USE_NANO:BOOL=ON -DOPENVDB_TOOL_USE_PNG:BOOL=ON -DPython_EXECUTABLE:FILEPATH=/usr/bin/python3.10 -DUSE_AX:BOOL=ON -DUSE_BLOSC:BOOL=ON -DUSE_EXPLICIT_INSTANTIATION:BOOL=ON -DUSE_EXR:BOOL=ON -DUSE_IMATH_HALF:BOOL=ON -DUSE_LOG4CPLUS:BOOL=ON -DUSE_NANOVDB:BOOL=ON -DUSE_NUMPY:BOOL=ON -DUSE_PNG:BOOL=ON ..`
3. Build with '....'

### Additional context
(Add any other context about the problem here.)

**Comment by malaterre** [comment]
For later reference:

-- Found LLVM: /usr/lib/llvm-14/cmake (found suitable version "14.0.6", minimum required is "10.0.0")

**Comment by malaterre** [comment]
`sizeof(void*)` is 4 on 32bits arches, while templates are only defined for:

```
template <size_t Bits> struct int_t;
template <> struct int_t<8>  { using type = int8_t;  };
template <> struct int_t<16> { using type = int16_t; };
template <> struct int_t<32> { using type = int32_t; };
template <> struct int_t<64> { using type = int64_t; };
```

**Comment by Idclip** [comment]
Thanks @malaterre! I think the logic here was wrong anyway, this void*'s should always alias to i8* in IR, regardless of the platform. Have implemented a fix
