### ISSUE TITLE
Failed to compile openvdb v4.x.x  with vs2012 in win 10 

### ISSUE THREAD

**Issue by kSpacer201** [AcademySoftwareFoundation/openvdb#154]
I tried to compile the openvdb with maya and met the errors. [ As I want to use it in the Maya2016,Maya2014]

E1. openvdb\Exception.h
    ... \Exceptions.h(46): error C2065: 'default' : undeclared identifier

E2.  '(' errror at  template
    Vec3.h(92): error C2958: the left parenthesis '(' found at .....\openvdb\math\vec3.h(92)'

I searched and found one  way to solve the E1  with  wrting some precompiled instructions, but was so confused the E2 template . I had these questions.

- Is it possible to compile openvdb4.x.x with vs2012 or vs2010 [some compilers not fully support c++11]?

- Is there any tips to sovle these problems ?

**Comment by danrbailey** [comment]
Our Maya support is not robust, but as our minimum Visual Studio version is now 2017, I assume this issue is now resolved. Re-open if not.
