### ISSUE TITLE
[BUILD] OpenVDB passes gcc style flags to MSVC

### ISSUE THREAD

**Issue by LazyDodo** [AcademySoftwareFoundation/openvdb#1546]
### Environment
**Operating System:** Win10
**Version / Commit SHA:** VDB 10.0
**CMake Version:** 3.24.2
**Compiler:** msvc 2019

### Describe the problem
When setting `-DOPENVDB_SIMD=SSE42` OpenVDB's cmake passes the GCC style flags directly to MSVC over in [CMakeLists.txt@386](https://github.com/AcademySoftwareFoundation/openvdb/blob/master/CMakeLists.txt#L386)

### To Reproduce
1. Build with `-DOPENVDB_SIMD=SSE42` or `-DOPENVDB_SIMD=AVX` with MSVC
2. `cl : Command line warning D9002: ignoring unknown option '-msse4.2' [c:\db\build\S\VS1564D\openvdb.vcxproj]`

### Additional context
MSVC doesn't have a flag for SSE42, but if you call the sse42 intrinsics like openvdb does the right opcodes will still be generated,  AVX can be enabled with `/arch:AVX` [source](https://learn.microsoft.com/en-us/cpp/build/reference/arch-x64?view=msvc-170)

**Comment by Idclip** [comment]
Hey @LazyDodo thanks for reporting this, this has now been fixed https://github.com/AcademySoftwareFoundation/openvdb/pull/1645 (though as an aside, the way we handle hardware instrumentation in general isn't correct and we're planning of restructuring this in the future)
