### ISSUE TITLE
TBB Version exceeds minimum version, but still erroneous

### ISSUE THREAD

**Issue by joerowelll** [AcademySoftwareFoundation/openvdb#1558]
### Environment
ubuntu 20.04
**CMake Version:** 3.25

### Describe the problem
when executing cmake .. in the build dir, I get the error as follows : 
```
  Could NOT find TBB (missing: Tbb_LIB_COMPONENTS) (found suitable version
  "2021.9", minimum required is "2020.2")
```
I built TBB from source and have tried the command : 
```
cmake -D CMAKE_INSTALL_PREFIX=$HOME/openvdb -D TBB_ROOT=/path/to/tbb/install ../ 
``` 
aswell. Wiht the path to tbb install as where it is built from source.
Surely my version exceeds minimum required version and should be ok?

**Comment by Idclip** [comment]
Hi @joerowelll,

Your TBB version should be fine. The actual error is `Could NOT find TBB (missing: Tbb_LIB_COMPONENTS)`. Usually this error also lists which components it couldn't find but these seem to be missing from the error message. Looking at our CI, it seems that the highest TBB version we test with is `2021.7` - I suspect something has changed in `2021.9` and our CMake will need to be updated. 

I can't actually even see a `2021.9` release of TBB here https://github.com/oneapi-src/oneTBB/releases ... how are you installing TBB?

**Comment by joerowelll** [comment]
I should have put the whole error, sorry. It lists what cannot be found afterwards.

**Comment by Idclip** [comment]
Thanks @joerowelll. I'm having trouble reproducing this. I'm testing on Ubuntu 20.04 with CMake 3.25.0 with the following:

```bash
git clone https://github.com/oneapi-src/oneTBB.git
cd oneTBB
git checkout 66c6d8e3305363642d6284410881fda82f5c9c96
mkdir .build
cd .build
cmake -DCMAKE_INSTALL_PREFIX=/path/to/tbb/install -DTBB_TEST=OFF ..
make install
```
```bash
git clone https://github.com/AcademySoftwareFoundation/openvdb.git
git checkout 2caed723981eb16799f825aeb35a1fd93e541383  # current master
cd openvdb
mkdir .build
cd .build
cmake -D TBB_ROOT=/path/to/tbb/install ..
```

What does your TBB install directory look like if you `tree /path/to/tbb/install` it? 
If you `cat CMakeCache.txt | grep TBB` in your openvdb build directory, what does those variables display?

**Comment by joerowelll** [comment]
When following that exactly, I still get the same error. 

The TBB Install dir. tree is rather large, Ive attached as a text file. 
[tbb_tree.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/10287018/tbb_tree.txt)

The  `cat CMakeCache.txt | grep TBB`  in the openvdb build dir. gives as follows:
TBB_LIB_COMPONENTS:UNINITIALIZED=/home/git/oneTBB/build 
TBB_ROOT:UNINITIALIZED=/home/joe/git/oneTBB
Tbb_INCLUDE_DIR:STRING=/home/joe/git/oneTBB/include
// for TBB, Blosc, IlmBase and OpenEXR. Boost must be
// for TBB. All other dependencies must be provided.
//Use TBB in building the NanoVDB library.
USE_TBB:BOOL=ON

**Comment by Idclip** [comment]
@joerowelll,

That directory you've `tree`'d is the repository directory where you cloned TBB. What you should be passing to OpenVDB's CMake is the location you specified to install TBB. For example:

```
git clone https://github.com/oneapi-src/oneTBB.git
cd oneTBB
echo $PWD # /Users/nicholasa/dev/oneTBB   <--- source directory
...
cmake -DCMAKE_INSTALL_PREFIX=/Users/nicholasa/dev/tbb_install   <---- install dir
```

Looking at the install dir you should see something like:

```
tree -d /Users/nicholasa/dev/tbb_install
.
├── include
│   ├── oneapi
│   │   └── tbb
│   │       └── detail
│   └── tbb
├── lib
│   ├── cmake
│   │   └── TBB
│   └── pkgconfig
└── share
    └── doc
        └── TBB
```

**Comment by joerowelll** [comment]
That a silly mistake on my part, thank you. 
Although if i now build oneTBB with ```cmake -DCMAKE_INSTALL_PREFIX=/usr/local/tbb_install ..```, and specify TBB_ROOT when building openvdb in the build directory with 
```cmake -D TBB_ROOT=/usr/local/tbb_install .. ```, I still get the same errors.
```CMake Error at /home/joe/cmake-install/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find TBB (missing: Tbb_LIB_COMPONENTS) (found suitable version
  "2021.9", minimum required is "2020.2")
Call Stack (most recent call first):
  /home/joe/cmake-install/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTBB.cmake:368 (find_package_handle_standard_args)
  openvdb/openvdb/CMakeLists.txt:133 (find_package)
```

and the ```tree /usr/local/tbb_install``` is an empty directory.  
Thank you for being so helpful.

**Comment by joerowelll** [comment]
Thats my silly mistake... thank you for your help !
