### ISSUE TITLE
[VolumeToMesh keep sharp]

### ISSUE THREAD

**Issue by MarcoWang1** [AcademySoftwareFoundation/openvdb#1566]
when I use VolumeToMesh in openVDB, how to keep sharp edges/features?
Why  did not you implement this algorithm in openVDB core library?
I know that openvdb_houdini have  a referenceMeshing method to keep sharp features.
But it is hard to understand and use because you need to install houdini library.

Do you have plans to write keep sharp functions in OpenVDB library?

**Comment by MarcoWang1** [comment]
why nobody reply?

**Comment by apradhana** [comment]
Hello, The Steering Committee currently does not have any plan to add this functionality in the OpenVDB core library at the moment. We welcome contributors to the sharpen feature to the core library.

**Comment by kmuseth** [comment]
The main reason openvdb does not support this feature out of the box is simply that our library does not have any acceleration structures for polygon meshes. Houdini has such an acceleration structure which is why this feature is available there. As such it would be fairly straight forward to add to other DCCs, e.g. Blender, but OpenVDB is not enough.

Cheers,
Ken

**Comment by apradhana** [comment]
Hi @MarcoWang1 . The implementation on how to generate an adaptive mesh is implemented [here](https://github.com/AcademySoftwareFoundation/openvdb/blob/master/openvdb_houdini/openvdb_houdini/GeometryUtil.h#L179-L269). What needs to be done is to change the use of Houdini’s `GU_Detail` with a mesh library that can compute normal and write into the primitive stored in the mesh. An example of an open source mesh library is [this one](https://geometry-central.net/).

**Comment by abdoulayediak** [comment]
Hi guys, I would like to try this feature, but can't figure out how to build openvdb_houdini (I am on Windows and getting openvdb core was pretty straigtforward with vcpkg). 

Can the openvdb_houdini folder be used like a header-only library or shall it be built? If so, can I build it directly or does it need the full Houdini software as a dependency? Any hint/doc link will be highly appreciated. Thanks.
