### ISSUE TITLE
[BUILD]Compile failed on windows 10(msvc2017), Error C2627

### ISSUE THREAD

**Issue by Wuxinberry** [AcademySoftwareFoundation/openvdb#1585]
### Environment
**Operating System:** Windows 11
**Version / Commit SHA:** VDB 10.0.1
**CMake Version:** 3.25.2
**Compiler:** msvc 2017

### Describe the problem
When execute command  `cmake --build . --parallel 4 --config Release --target install`, folllowing error occurs. I also tried to use msvc2017 to generate the solution, same confusing problem still exist and failed to build.
It points to <algorithm.h> file, line 5386: "_NOEXCEPT_COND(_NOEXCEPT_OPER(_Left < _Right))". And I guess it shall caused by some file that includes the <algorithm.h>.
> Error C2676 Binary '<': 'const _Ty' does not define the operator or a conversion to a type that can be received by a predefined operator openvdb_shared
> Error C2056 invalid expressions
> Error C2088 invalid for class

### To Reproduce
1. Checkout repo
2. Run CMake `cmake --build . --parallel 4 --config Release --target install`
3. Build with cmake or msvc2017(generate solution)

**Comment by Idclip** [comment]
Hi @Wuxinberry, are you using OpenVDB with OpenCV by any chance? Try turning on conformance mode in VS2017: https://github.com/gabime/spdlog/issues/1491#issuecomment-674867060

**Comment by Idclip** [comment]
Closing, please re-open if this is still an issue
