### ISSUE TITLE
Point Attributes not working/building

### ISSUE THREAD

**Issue by cgolchert** [AcademySoftwareFoundation/openvdb#1594]
### Environment
Win10
vdb 10.x
VS2022
dep. abd VDB build from vcpkg

### Describe the bug
The cookbook example for point attributes doesn't work.
[https://www.openvdb.org/documentation/doxygen/codeExamples.html#sPointsConversion](url)

The line:
openvdb::points::TypedAttributeArray<float, Codec>::registerType();

Will cause linking errors.

### To Reproduce
1) try to build the "Converting Point Attributes" given as documentation for Points

### Expected behavior
Expect it to compile/build

### Additional context
  

> 1>( error LNK2001: unresolved external symbol "__declspec(dllimport) protected: __cdecl openvdb::v10_0::points::AttributeArray::AttributeArray(class openvdb::v10_0::points::AttributeArray const &,class tbb::spin_mutex::scoped_lock const &)" (__imp_??0AttributeArray@points@v10_0@openvdb@@IEAA@AEBV0123@AEBVscoped_lock@spin_mutex@tbb@@@Z)
> 1>  Hint on symbols that are defined and could potentially match:
> 1>    "__declspec(dllimport) public: __cdecl openvdb::v10_0::points::AttributeArray::AttributeArray(void)" (__imp_??0AttributeArray@points@v10_0@openvdb@@QEAA@XZ)
> 1>C:\dev\x64\Release\cb.exe : fatal error LNK1120: 1 unresolved externals
> 1>Done building project "OpenVDB_Cookbook.vcxproj" -- FAILED.

**Comment by Idclip** [comment]
Please include how you're building VDB (from source/vcpkg?) and if possible the msbuild CLI output commands (not just their errors)

**Comment by cgolchert** [comment]
vcpkg built openvdb and dependencies. 

The ouput Iget is:
`Build started...
1>------ Build started: Project: OpenVDB_Cookbook, Configuration: Release x64 ------
1>Sandbox.cpp
1>TBB Warning: tbb/task_scheduler_init.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.
1>Sandbox.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) protected: __cdecl openvdb::v10_0::points::AttributeArray::AttributeArray(class openvdb::v10_0::points::AttributeArray const &,class tbb::spin_mutex::scoped_lock const &)" (__imp_??0AttributeArray@points@v10_0@openvdb@@IEAA@AEBV0123@AEBVscoped_lock@spin_mutex@tbb@@@Z)
1>  Hint on symbols that are defined and could potentially match:
1>    "__declspec(dllimport) public: __cdecl openvdb::v10_0::points::AttributeArray::AttributeArray(void)" (__imp_??0AttributeArray@points@v10_0@openvdb@@QEAA@XZ)
1>C:\dev\modo\VDB-Suite\Project\VDB-Suite\x64\Release\cb.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "OpenVDB_Cookbook.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 10:50 PM and took 15.582 seconds ==========`

**Comment by cgolchert** [comment]
It will build without a problem if I leave out the `openvdb::points::TypedAttributeArray` lines

**Comment by cgolchert** [comment]
Found a workaround...  I'm closing this.
