### ISSUE TITLE
[BUG] msvc link error about imath

### ISSUE THREAD

**Issue by freestriker** [AcademySoftwareFoundation/openvdb#1611]
### Environment
**Operating System:win11 22h2
**Version / Commit SHA:10.0.1
**Other:latest vs2022 with its msvc (e.g compiler, C++ standard etc.)

### Describe the bug
(A clear and concise description of what the bug is.)
build the openvdb x64-windows by vcpkg, run the cookbook's example code, showed as follows: 
EXEC : error : main.cpp.obj : error LNK2001: unresolved external symbol imath_half_to_float_table
build\windows\x64\debug\OpenVDBTest.exe : fatal error LNK1120: 1 unresolved externals

### To Reproduce
1. Build with vcpkg install openvdb --triplet=x64-windows
2. Run code from https://www.openvdb.org/documentation/doxygen/codeExamples.html in vs2022 debug mode
3. See error

### Expected behavior
(A clear and concise description of what you expected to happen.)
no link error

### Additional context
(Add any other context about the problem here.)
found a solution in forum to skip this error: https://groups.google.com/g/openvdb-forum/c/51664ugGfIs/m/pfrO462vAAAJ
add "#define IMATH_HALF_NO_LOOKUP_TABLE" before "#include <openvdb/openvdb.h>", the cookbook's code can link and run successfully.

**Comment by Idclip** [comment]
Hey @freestriker, thanks for this, this should now be fixed on master - we always explicitly disable the inbuilt half lookup table now
