### ISSUE TITLE
[BUILD]

### ISSUE THREAD

**Issue by RemoCharlie** [AcademySoftwareFoundation/openvdb#1661]
### Environment
**Operating System:** (e.g. Windows 2019, macOS-10.15, Linux CentOS 7.4)
**Version / Commit SHA:** (e.g VDB 7.2, SHA: 1a2b3c4d5e...)
**CMake Version:** (e.g. 3.18)
**Compiler:** (e.g. gcc 10, msvc 2019)

### Describe the problem
(A clear and concise description of the encountered issue.)

### To Reproduce
1. Checkout repo '...'
2. Run CMake '....'
3. Build with '....'

### Additional context
(Add any other context about the problem here.)

**Comment by Idclip** [comment]
Closing due to no infor
