### ISSUE TITLE
[BUILD] Error on make_index_sequence_impl

### ISSUE THREAD

**Issue by cjsb** [AcademySoftwareFoundation/openvdb#1665]
### Environment
**Operating System:** Windows 10
**Version / Commit SHA:** Latest Version

### Describe the problem
I am trying to run the latest version but I am getting a couple of errors:
1) error C2672: 'openvdb::v10_0::make_index_sequence_impl': no matching overloaded function found
2) error C2975: 'N': invalid template argument for 'openvdb::v10_0::make_index_sequence_impl', expected compile-time constant expression

To create the project, I used CMAKE gui, without adding any new option. How can I solve this issue?

**Comment by Idclip** [comment]
Hey @cjsb,

In the CMake output you should see something like `The CXX compiler identification is` - what's the compiler and version number it reports? Can you try and make sure you've installed any compiler updates (I'm assuming MSVC) if it's not up to date?

**Comment by Idclip** [comment]
Closing, but please re-open if the problem still persists
