### ISSUE TITLE
[BUG] MINIMUM_GCC_VERSION is incorrect

### ISSUE THREAD

**Issue by mwestphal** [AcademySoftwareFoundation/openvdb#1747]
### Environment
**Operating System:** Linux
**Version / Commit SHA:** 11.0
**Other:** gcc

### Describe the bug
MINIMUM_GCC_VERSION is currently too high, with value `9.3.1`.
As the comment above in cmake/config/OpenVDBVersions.cmake states:

```
  # @Note  Compiler versions are not really a hard and fast rule, you just need
  # a compiler with complete support for our MINIMUM_CXX_STANDARD (currently 17).
  # What's usually important is that the version of libstdc++ and glibc in use
  # matches. Compilers other than GCC should provide options to ensure this
  # targetting e.g. --gcc-toolchain and -fgnuc-version with Clang.
```

I've been modifying the value to 8.4.0 and it works fine.

**Comment by Idclip** [comment]
Hi @mwestphal,

We're working off the following comment in the C++ 17 status page from the GCC manual https://gcc.gnu.org/projects/cxx-status.html:

> Some C++17 features are available since GCC 5, but support was experimental and the ABI of C++17 features was not stable until GCC 9. 

The minor/patch version numbers were chosen to match the VFX platform, but strictly speaking this version could indeed by `9.0.0`. From the comment quoted above, I don't think we want to drop it further. You're welcome to use earlier versions and can define the `-D DISABLE_DEPENDENCY_VERSION_CHECKS=OFF` to suppress these requirements, but these are the minimum versions we guarantee support for

**Comment by mwestphal** [comment]
`-D DISABLE_DEPENDENCY_VERSION_CHECKS=OFF` I missed this, indedd, an acceptable fix.
