### ISSUE TITLE
[BUILD] Python bindings fail to build for version 3.11

### ISSUE THREAD

**Issue by StefanKarlsson987** [AcademySoftwareFoundation/openvdb#1803]
### Environment
**Operating System:** Ubuntu 22.04
**Version / Commit SHA:** VDB 11.0.0 AND current ToT (sha 08409f0044afe0b188398dd2b27af7d8edb8c554)

### Describe the bug
When trying to build with the python bindings, the process fails with various error messages connected to "PyFrameObject".
This has been tested for python version 3.11.7 and 3.11.9.

see the [make_output.log](https://github.com/AcademySoftwareFoundation/openvdb/files/15194074/make_output.log)

Likely root cause: PyFrameObject has been removed from python version 3.11

### To Reproduce
`cmake .. -D CMAKE_INSTALL_PREFIX=$HOME/openvdb -D CMAKE_BUILD_TYPE=Release -D OPENVDB_BUILD_PYTHON_MODULE=ON -D Python_EXECUTABLE=/path/to/python/python3.11
`
`make -j$(nproc) 2>&1 | tee make_output.log`

### Expected behavior
I expected no errors reported, and then have working python bindings that would work on my python 3.11 environment.

**Comment by StefanKarlsson987** [comment]
The reason I do not want to revert to earlier version of python, is that I plan to use this from inside of Blender. Blender 4.1 comes shipped with python 3.11.7.

I already have a large addon created in the python API for blender, and would like to add proper VDB processing to it, which Blender currently does not have natively (unlike Maya).

**Comment by Idclip** [comment]
Closing this as it seems as though you managed to resolve your issue? Yes, using `apt-get` assumes that you're installing our your dependencies through `apt-get` as this is how the `apt` repositories are configure; the set of software they provided is tested to work together. If you instead mix dependencies, such as a newer version of Python with those from`apt` then your build solution is not guaranteed to work and you may find you need to also upgrade other dependencies too.
