### ISSUE TITLE
[BUG] Unable to load plugin: USD.plugin

### ISSUE THREAD

**Issue by niteshpatel31** [AcademySoftwareFoundation/openvdb#1854]
### Environment
**Operating System:** Linux Endeavor OS 
**Version / Commit SHA:** OpenVDB 11.0.0
**Other:** installed from AUR using Pacman package manager

### Describe the bug
whenever I open the **Davinci Resolve** Editor it says :-
**/opt/resolve/libs/Fusion/Plugins/USD/**
**libopenvdb.so.10.0: undefined symbol: ZN3tbb10interface78internal 15task a**

### To Reproduce
1. Download the **Davinci Resolve from AUR or tarball tar.gz**
2. Run **Davinci Resolve**
3. See error

### Expected behavior
**GUI Instability** in Davinci Resolve.

### Additional context
![Screenshot_20240623_135221](https://github.com/AcademySoftwareFoundation/openvdb/assets/150846500/e5494e7d-702f-48e8-a0d0-2683710feee8)

**Comment by exilonium** [comment]
how did you fixed it?

**Comment by niteshpatel31** [comment]
you can download and install openvdb from aur that updates libopenvdb.so error in davinci resolve

**Comment by exilonium** [comment]
it don't seem to work

**Comment by niteshpatel31** [comment]
If you can try to **reinstall the operating system**, then **update and upgrade all the packages** and **install from AUR(for Arch) or the tarball.** I think it should work, my friend faced the same issue even after installing the libopenvdb.so then he reinstalled the OS updated the packages, and installed from tarball and it did work.


**Otherwise, post this issue to the Blackmagic design forum.**

**Comment by exilonium** [comment]
reinstalling the whole system doesn't make sense to fix a minor software bug.

anyways just found out that my graphics driver is not supported.
