### ISSUE TITLE
How does FVDB average pooling work? 

### ISSUE THREAD

**Issue by nissmar** [AcademySoftwareFoundation/openvdb#1873]
Hi, 

I am trying to implement an average pooling filter on a sparse VDBTensor. In regular PyTorch I would use `torch.nn.AvgPool3d(kernel, kernel, divisor_override=1)` and divide the result by the number of active values if any (between 1 and $kernel ^3$). 
However I cannot replicate that with `AvgPool` in fvdb. 

I also tried to define my own convolution with: 

```
conv = SparseConv3d(n_c, n_c, kernel, kernel, False) 
with torch.no_grad():
    conv.weight[:] = 0
    for i in range(n_c):
        conv.weight[i,i,:] = 1.
sum_pool = conv(vdbtensor).jdata # vdbtensor.feature[...,  n_c-1]=1 to count the number of active sites
sum_pool = sum_pool[..., :n_c-1]/sum_pool[..., n_c-1, None]
```
But I could not match what I obtain in the dense case. 

How is `AvgPool` supposed to work?

**Comment by fwilliams** [comment]
Hi @nissmar 

Thanks for the question! There are two ways to average pool in fvdb. (1) Directly using the `GridBatch` and a feature `JaggedTensor` or (2) using `fvdb.nn`

### Option 1:
The first uses a `GridBatch` directly via `GridBatch.avg_pool` whose signature is:
```python
def avg_pool(self, pool_factor: Vec3iOrScalar, data: JaggedTensorOrTensor, stride: Vec3iOrScalar = 0, coarse_grid: Optional[GridBatch] = None) ->  Tuple[JaggedTensor, GridBatch]
```
The arguments are:
 * `pool_factor`: the width/height/depth of the filter to pool in (either a triple or a scalar)
 * `data`: a `JaggedTensor` of features per-grid in the batch to be pooled
 * `stride`: a stride for the pooling
 * `coarse_grid`: (optional) -- if you've precomputed the coarse pooled grid, you can pass it in and it won't be recomputed
The function returns:
 * `pooled_data`: a `JaggedTensor` of average pooled feature for each voxel in the output grids
 * `out_grids`: a `GridBatch` of pooled grids.

### Option 2:
Using [`fvdb.nn.AvgPool`](https://github.com/voxel-foundation/fvdb/blob/1dc0cf7a9fd42db0e58d650da9abd207b0fa6701/fvdb/nn/modules.py#L71) whose constructor takes in a pooling size and stride, and whose `forward` function takes in a `VDBTensor`.

**Comment by nissmar** [comment]
Thank you!
