### ISSUE TITLE
[BUILD] fvdb not installable

### ISSUE THREAD

**Issue by JamesPerlman** [AcademySoftwareFoundation/openvdb#1878]
### Environment
Windows 11, python 3.11.9, miniconda3 (conda 24.7.1)

### Describe the problem
In [openvdb/fvdb/README.md](https://github.com/AcademySoftwareFoundation/openvdb/blob/feature/fvdb/fvdb/README.md?plain=1#L22) there is an incomplete instruction:
> fVDB is provided as an installable python package from *[todo: insert package distributor]*.

In addition, the conda install command given in the README does not appear to be working.

### To Reproduce
1. As per the README, run `conda install -c jswartz fvdb`
2. See the `PackagesNotFoundError` for `fvdb`

### Additional context
I am really looking forward to using fVDB!

**Comment by swahtz** [comment]
I corresponded with James offline and advised that building for Windows is currently not supported.  I've also unfortunately left instructions for a test build of fVDB up on the docs which I'll remove.

**Comment by OasisYang** [comment]
Hi, I tried the same command `conda install -c jswartz fvdb` on Linux and got the same issue `PackagesNotFoundError: The following packages are not available from current channels:- fvdb`

**Comment by swahtz** [comment]
Hi @OasisYang, at the moment we don't have packaged builds distributed for fvdb.  The build instructions should still be relevant and work but the `conda` command in the README is an instruction from an old test package.  This conda command information will be removed shortly, sorry for the confusion.
