### ISSUE TITLE
[BUG]Nanovdb: Invalid code in GridBuilder fails to compile with clang19

### ISSUE THREAD

**Issue by mont29** [AcademySoftwareFoundation/openvdb#1976]
### Environment
**Operating System:** Linux Debian Testing, x86_64
**Version / Commit SHA:** VDB 11.0.0
**Other:** Clang-19

### Describe the bug
Trying to build a project using NanoVDB with Clang19 fails with following error:

```
[...]/lib/linux_x64/openvdb/include/nanovdb/util/GridBuilder.h:1161:72: error: no member named 'isActive' in 'LeafNode<BuildT>'
 1161 |         bool isActive() const { NANOVDB_ASSERT(*this); return mParent->isActive(mPos);}
      |                                                               ~~~~~~~  ^
```

Issue discovered when trying to build Blender with Clang 19.

This is related to [this change](https://releases.llvm.org/19.1.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics:~:text=Clang%20now%20looks%20up%20members%20of%20the%20current%20instantiation%20in%20the%20template%20definition%20context%20if%20the%20current%20instantiation%20has%20no%20dependent%20base%20classes.) in the compiler (see also [the PR](https://github.com/llvm/llvm-project/pull/84050)).

**Comment by dgovil** [comment]
Bastien, I just put up a PR at https://github.com/AcademySoftwareFoundation/openvdb/pull/1977 that should resolve this for you.
