### ISSUE TITLE
[BUG] I have train colmap failed in example 3dgs folder, remind me "circular import", why?

### ISSUE THREAD

**Issue by fy2462** [AcademySoftwareFoundation/openvdb#1981]
### Environment
**Operating System:** (Linux Ubuntu 7.4)
**Version / Commit SHA:** (e.g VDB 7.2, SHA: 1a2b3c4d5e...)
**Other:** (e.g compiler, C++ standard etc.)

### Describe the bug
(A clear and concise description of what the bug is.)

### To Reproduce
1. Build with '...'
   I running the fvdb in docker container
3. Run function '....'
   pyrhon train_colmap.py --data-path data/360_v2/room
5. See error
![image](https://github.com/user-attachments/assets/393b98ee-a02b-47fd-bf2f-1204bd64d919)

**Comment by swahtz** [comment]
Hi @fy2462 I tried to replicate this issue by building the docker container but I couldn't get this same error.  I did get another error about how we were missing `fvdb.optim` when installing fvdb.  I've just pushed some changes which has fixed that issue, could you give that a try with the changes we've pushed up?  Thank you
