### ISSUE TITLE
Case sensitivity in CMakelists file

### ISSUE THREAD

**Issue by dokipen3d** [AcademySoftwareFoundation/openvdb#206]
Trying to build on kubuntu 16.04 with cmake 3.9 and gcc 4.8.3, I am getting cmake configure errors due the the library (eg Ilmbase_HALF_LIBRARY vs ILMBASE_HALF_LIBRARY) containing lowercase characters. changing them to upper case works. I'll see if I can do a PR later.

**Comment by Delwin9999** [comment]
There's also the fact that IlmBase is the correct capitalization - and the cmake references it as ILMBase

**Comment by Idclip** [comment]
I believe this should be resolved across all usages of IlmBase in our CMake using the capitalisation @Delwin9999 mentioned. Please re-open if this is still not the case!
