### ISSUE TITLE
Houdini 16.5 boost linking

### ISSUE THREAD

**Issue by dokipen3d** [AcademySoftwareFoundation/openvdb#216]
Hi all 

I was building on OSX for houdini 16.5 and ran into some stumbling blocks when compiling the houdini SOPs because of the changes to houdini's boost. Some sops seem to use the houdini error logging which uses hboost. Also the vector merge SOP uses boost regex which didn't link straight away.

Adding these to the openvdb_houdini CMakeLists target link libraries sorted everything out. Does someone want to do some fancier CMakelist file editing?

example line 133...

TARGET_LINK_LIBRARIES ( openvdb_houdini
  ${OPENVDB_SHARED_LIB}
  HoudiniPRM
  HoudiniGEO
  HoudiniUT
  HoudiniOP2
  HoudiniOP3
  boost_regex  
  hboost_iostreams
  hboost_system
  )

**Comment by Idclip** [comment]
Hey @dokipen3d this should now be resolved. Closing, but let me know if you still have any issues with the OpenVDB Houdini CMake builder
