### ISSUE TITLE
openvdb failed to build with gcc 8.0.1

### ISSUE THREAD

**Issue by luyatshimbalanga** [AcademySoftwareFoundation/openvdb#225]
Hello, 
openvdb failed to build with the latest stable release of gcc i.e. 8.0.1
https://koji.fedoraproject.org/koji/taskinfo?taskID=25736367 (select one of architecture i.e x86-64 to view the build.log)

although it successfully build with gcc 7.1.1
https://koji.fedoraproject.org/koji/taskinfo?taskID=25736526

It appears the newer gcc 8.0.1 caught some incompatibilities that need to be addressed as seen on [build.log](https://kojipkgs.fedoraproject.org//work/tasks/6368/25736368/build.log)

The issue affects all version of openvdb.

**Comment by OpenVDB-DevTeam** [comment]
That build failure (in `pyFloatGrid.cc`) was fixed in commit 1856881.  Can you give that a try?

**Comment by luyatshimbalanga** [comment]
I confirm the fix solved the issue related to that build failure. 
https://koji.fedoraproject.org/koji/taskinfo?taskID=25869233

**Comment by OpenVDB-DevTeam** [comment]
Thanks for the confirmation.

We'll look into fixes for the warnings as well.

**Comment by luyatshimbalanga** [comment]
I am closing this report as resolved as the issue no longer appears on gcc 9+.
