### ISSUE TITLE
"make test" fails, but then passes if run manually 

### ISSUE THREAD

**Issue by TheOtherDave** [AcademySoftwareFoundation/openvdb#228]
Hi, I'm trying to compile & install openvdb, and "make test" fails both of the tests.

Looking at /path/to/openvdb/build/Testing/Temporary/LastTest.log, it appears that "vdb_unit_test" very nearly passes -- only 21 tests barely fail the double equality assertion test. And that result is replicated by manually running "/path/to/openvdb/build/openvdb/vdb_test".
Is this normal, and can I ignore the failed tests?

"pytest" is more interesting... When run as part of the "make test" command, it immediately fails with this error:
`Traceback (most recent call last):
  File "/path/to/openvdb/openvdb/python/test/TestOpenVDB.py", line 41, in <module>
    import studioenv
ImportError: No module named studioenv
<end of output>
`
But when I run the test manually by copying and pasting the command from the failed test log: "/usr/bin/python" "/path/to/openvdb/openvdb/python/test/TestOpenVDB.py", it passes all 16 tests.

What's "studioenv"? I've been googling for a python module with that name for a while, and can't find anything. Second, why would the test suddenly start working when I ran it manually?

Thanks

**Comment by MichaelQuell** [comment]
The test fails for me too, but pasting the command still leads to the same error with me.

**Comment by Idclip** [comment]
With the recent changes and ports to CMake, the test commands have been changed and I believe this is resolved. Closing, but feel free to re-open should this issue persist
