### ISSUE TITLE
OpenEXR&IlmBase's private preprocessor definition HALF_EXPORTS leaks to OpenVDB, causing unresolved external symbol _toFloat & _eLut

### ISSUE THREAD

**Issue by ghost** [AcademySoftwareFoundation/openvdb#247]
Building Environment:
- Windows 10 version 1803
- Visual Studio 2015 Update 3
- CMake 3.11.4
- Source code downloaded from official OpenVDB site (version 5.1.0) or master branch from here (version 5.2)
- OpenEXR&IlmBase is downloaded from the current dev branch from https://github.com/openexr/openexr
- Both OpenVDB and OpenEXR&IlmBase are built under Debug x64 DLL mode in VS

CMake command line for IlmBase:
`cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=C:\...\openexr-develop\IlmBase\install_ -G"Visual Studio 14 2015 Win64" ..`
CMake command line for OpenEXR:
`cmake -DBUILD_SHARED_LIBS=ON -DILMBASE_PACKAGE_PREFIX=C:\...\openexr-develop\IlmBase\install_ -DCMAKE_INSTALL_PREFIX=C:\...\openexr-develop\OpenEXR\install_ -DZLIB_LIBRARY=C:\...\zlib-1.2.11\install\lib\zlib.lib -DZLIB_INCLUDE_DIR=C:\...\zlib-1.2.11\install\include -G"Visual Studio 14 2015 Win64" ..`
CMake command line for OpenVDB:
`cmake -DOPENVDB_ABI_VERSION_NUMBER=5 -DBUILD_SHARED_LIBS=ON -DGLEW_LOCATION=C:\...\glew-2.1.0-src -DBLOSC_LOCATION=C:\...\c-blosc-master\install -DTBB_LOCATION=C:\...\tbb2018_20180618oss -DZLIB_ROOT=C:\...\zlib-1.2.11\install -DILMBASE_LOCATION=C:\...\openexr-develop\IlmBase\install_ -DOPENEXR_LOCATION=C:\...\openexr-develop\OpenEXR\install_ -DOPENVDB_BUILD_DOCS=ON -DCPPUNIT_LOCATION=C:\...\cppunit-1.12.1 -G"Visual Studio 14 2015 Win64" ..
`
A few modifications were made inside VS in order to proceed:
- change link input tbb.lib to tbb_debug.lib
- Add /bigobj as an additional compiling option

When building `openvdb_shared` project in VS, I got the following error:
> 1>------ Build started: Project: openvdb_shared, Configuration: Debug x64 ------
> 1>     Creating library C:/.../openvdb-5.1.0/build/openvdb/Debug/openvdb.lib and object C:/.../openvdb-5.1.0/build/openvdb/Debug/openvdb.exp
> 1>points.obj : error LNK2001: unresolved external symbol "private: static union half::uif const * const half::_toFloat" (?_toFloat@half@@0QBTuif@1@B)
> 1>openvdb.obj : error LNK2001: unresolved external symbol "private: static union half::uif const * const half::_toFloat" (?_toFloat@half@@0QBTuif@1@B)
> 1>points.obj : error LNK2001: unresolved external symbol "private: static unsigned short const * const half::_eLut" (?_eLut@half@@0QBGB)
> 1>openvdb.obj : error LNK2001: unresolved external symbol "private: static unsigned short const * const half::_eLut" (?_eLut@half@@0QBGB)
> 1>C:\\...\openvdb-5.1.0\build\openvdb\Debug\openvdb.dll : fatal error LNK1120: 2 unresolved externals
> ========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

After some analysis, the error arises from the presence of a preprocessor definition `HALF_EXPORTS`:
![image](https://user-images.githubusercontent.com/26125798/42433410-41e63cd4-831d-11e8-83b7-c7b815d5ab4e.png)
If I removed this preprocessor definition, openvdb_shared project builds successfully in VS. HALF_EXPORTS is set only by CMake for the `Half` project itself in IlmBase in order to cause symbols to export. It is done in C:\\...\openexr-develop\IlmBase\Half\CMakelists.txt, line 43. The definition is marked private:
`  TARGET_COMPILE_DEFINITIONS ( Half PRIVATE HALF_EXPORTS )`

I think it should not be the OpenEXR&IlmBase's problem to leak HALF_EXPORTS because there is another famous project that uses OpenEXR&IlmBase: OpenImageIO. If IlmBase leaks HALF_EXPORTS, it should appear in the OIIO project too. But there is no HALF_EXPORTS in OIIO. So I think it should be OpenVDB's problem. All the builds are clean, that is, there is no cache residues affecting the build.

So, could you please figure out how the preprocessor definition `HALF_EXPORTS` is leaked from `IlmBase` to `OpenVDB` VS solution, and how to fix it? Please let me know if you need other info to troubleshoot the issue. A reference to a related OpenEXR&IlmBase issue ticket is here: https://github.com/openexr/openexr/issues/302. Thank you.

**Comment by Idclip** [comment]
User has been deleted - but this problem is now resolved. A line in the older root CMakeLists.txt of OpenVDB (pre v6.1) for windows builds was adding the define:
```
IF (WIN32)
  ADD_DEFINITIONS ( -D_WIN32 -DNOMINMAX -DHALF_EXPORTS -DOPENVDB_DLL )
...
```
