### ISSUE TITLE
Houdini 16.5 + Boost 

### ISSUE THREAD

**Issue by dokipen3d** [AcademySoftwareFoundation/openvdb#260]
Now that houdini doesn't ship with boost, compiling openvdb with SOPs doesn't work with the current CmakeLists.txt.

If we have the OPENVDB_BUILD_HOUDINI_SOPS option on, then the INCLUDE_DIRECTORIES for boost on line 110 doesn't seem to work properly. I get an error with platform.h not being able to find boost/cstdint.hpp. bringing that INCLUDE_DIRECTORIES line out of the IF of the cmake, I dont get that error.

I'm on kubunti 16.04, cmake 3.11.4.

**Comment by havejoy** [comment]
I have encountered the same problem as yours, have u fix it now?

**Comment by Idclip** [comment]
This should now be fixed - and as of writing this, the minimum Houdini version is 17 so this is a bit old! Closing, but please re-open if this is still a problem with the latest releases of vdb and houdini
