### ISSUE TITLE
Undefined symbol  in pyopenvdb

### ISSUE THREAD

**Issue by Alobal123** [AcademySoftwareFoundation/openvdb#283]
Hello,
I am having trouble running the python part of the library. ./vdb_test runs fine, but the python test crashes on importing pyopenvdb with following message:

Traceback (most recent call last):
  File "openvdb_test.py", line 4, in <module>
    import pyopenvdb as vdb
ImportError: /usr/include/openvdb/openvdb/pyopenvdb.so: undefined symbol: _ZN5boost6python5numpy6detail13get_int_dtypeILi64ELb0EEENS1_5dtypeEv

I suspect this have something to do with wrong paths pointing to boost library, but cannot solve it.
Thank you for help!

**Comment by patilpratikg** [comment]
I am facing same issue.

**Comment by Alobal123** [comment]
I found a solution actually, addng this line to makefile:
 BOOST_PYTHON_LIB := -lboost_python2.7 -lboost_numpy-py27

**Comment by Idclip** [comment]
A fix for this is in PR #503 using the updated CMake build

**Comment by Idclip** [comment]
Merged with #503
