### ISSUE TITLE
Reading from openvdb::points::AttributeArray with uknown underlying type

### ISSUE THREAD

**Issue by ongamex** [AcademySoftwareFoundation/openvdb#351]
Hi all,

I'm writing an importer of *.vdb files in my software and I'm struggling with importing that data.
What I'm doing is I import attribute channels by name(for example id).
I want to read that id as int64 as this is the type that I'm using, however the channel could be stored as int short or even something else.
I failed to find a way to get the underlying data in a sinple way so I've decided to write a wrapper around openvdb::points::AttributeArray, which creates several openvdb::points::AttributeHandle<T>, based on the types that I'm expecting, and It got quite a bit complicated, and I decided that is waaaaaaay to much code for just getting an integer?

Is there a more simple API that I'm missing?

**Comment by danrbailey** [comment]
Hi @ongamex, 

Typically what we would do is put the logic that contains the ValueType into a templated function or class so you can instantiate it with all integer types you wish to support then simply cast to an int64 on access:

```
template <typename ValueType>
void myFunction(const points::PointDataGrid& points)
{
    auto leaf = points.constTree().cbeginLeaf();
    auto handle = points::AttributeHandle<ValueType>::create(
        leaf->constAttributeArray("id"));
    for (auto iter = leaf->beginIndexOn(); iter; ++iter) {
        int64_t id = static_cast<int64_t>(handle.get(*iter));
    }
}

auto leaf = points.constTree().cbeginLeaf();
const auto& array = leaf->constAttributeArray("id");

if (array.hasValueType<int16_t>())         myFunction<int16_t>(points);
else if (array.hasValueType<int32_t>())    myFunction<int32_t>(points);
else if (array.hasValueType<int64_t>())    myFunction<int64_t>(points);
```

However, the library does offer an alternative, which is to use compression codecs to downgrade the storage requirements for your arrays. This is currently done for float -> half using the TruncateCodec. Here's an alternative implementation for the above:

```
template <StorageType>
struct IdCodec
{
    static void decode(const StorageType& data, const int64_t& value)
    {
        value = static_cast<int64_t>(data);
    }
    static void encode(const int64_t& value, const StorageType& data)
    {
        data = static_cast<StorageType>(value);
    }
    static const char* name() { return "id"; }
};
```

Then your register your new types (int64_t with no codec is registered by default):

```
points::TypedAttributeArray<int64_t, IdCodec<int32_t>>::registerType();
points::TypedAttributeArray<int64_t, IdCodec<int16_t>>::registerType();
```

And append your new attribute such as:

```
points::appendAttribute<int64_t, IdCodec<int16_t>>(points.constTree(), "id");
```

And that would allow you to avoid the need for any templating in the code itself as the handle doesn't need to know what the codec is:

```
void myFunction(const points::PointDataGrid& points)
{
    auto leaf = points.constTree().cbeginLeaf();
    auto handle = points::AttributeHandle<int64_t>::create(
        leaf->constAttributeArray("id"));
    for (auto iter = leaf->beginIndexOn(); iter; ++iter) {
        int64_t id = handle.get(*iter);
    }
}

myFunction(points);
```

Just be aware that with this approach, you need to make sure these new types are registered before attempting any I/O, so if you're reading into a third-party application, you'll need to make sure you explicitly register them.

**Comment by ongamex** [comment]
Thank you, I'll give it a try!
