### ISSUE TITLE
PointsToMask::addPoints assumes PointListT::getPos is of type Vec3R

### ISSUE THREAD

**Issue by ongamex** [AcademySoftwareFoundation/openvdb#361]
PointsToMask::addPoints assumes PointListT::getPos is of type Vec3R.
I'd guess that this is an error as everything else in the API works with templates.

**Comment by Idclip** [comment]
Thanks @ongamex, this has now been fixed https://github.com/AcademySoftwareFoundation/openvdb/pull/1128
