### ISSUE TITLE
Build failed in windows  with ilmbase NOT Found.

### ISSUE THREAD

**Issue by Danielhu229** [AcademySoftwareFoundation/openvdb#429]
How to reproduce:

```cmd
vcpkg install boost zlib blosc openexr tbb
vcpkg integrate install
git clone git@github.com:AcademySoftwareFoundation/openvdb.git
cd openvdb
mkdir build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=<PATH_TO_VCPKG>\scripts\buildsystems\vcpkg.cmake ..
```

Output:
```cmd
 cmake -DCMAKE_TOOLCHAIN_FILE=D:/Library/vcpkg/scripts/buildsystems/vcpkg.cmake ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.15063.
-- CMake Build Type: Release
-- Configuring for OpenVDB Version 6.1.1
-- Configuring for OpenVDB ABI Version 6
-- ----------------------------------------------------
-- ------------- Configuring OpenVDBCore --------------
-- ----------------------------------------------------
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find IlmBase (missing: IlmBase_INCLUDE_DIR IlmBase_LIB_COMPONENTS
  Half) (Required is at least version "2.2")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindIlmBase.cmake:293 (find_package_handle_standard_args)
  D:/Library/vcpkg/scripts/buildsystems/vcpkg.cmake:234 (_find_package)
  openvdb/CMakeLists.txt:77 (find_package)


CMake Warning (dev) in cmake/FindIlmBase.cmake:
  Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
  and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  The included script

    D:/Projects/openvdb/cmake/FindIlmBase.cmake

  affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
  compatibility, so the effects are applied to the including context.
Call Stack (most recent call first):
  D:/Library/vcpkg/scripts/buildsystems/vcpkg.cmake:234 (_find_package)
  openvdb/CMakeLists.txt:77 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "D:/Projects/openvdb/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Danielhu229** [comment]
BTW, I have installed ilmbase

**Comment by Idclip** [comment]
Please see the sections on locating dependencies with OpenVDB's CMake here:
https://www.openvdb.org/documentation/doxygen/build.html#buildDependencies
https://www.openvdb.org/documentation/doxygen/build.html#buildTroubleshooting

You can provide the installation of IlmBase with `-DILMBASE_ROOT=/path/to/ilmbase`

Here's a typical example CMake command from our Windows CI:
```
cmake \ 
-G"Visual Studio 15 2017 Win64" \ 
-DCMAKE_CONFIGURATION_TYPES=%CONFIGURATION% \ 
-DCMAKE_INSTALL_PREFIX=%APPVEYOR_BUILD_FOLDER%\install \ 
-DCMAKE_TOOLCHAIN_FILE=C:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake \ 
-DOPENVDB_ABI_VERSION_NUMBER=6 \ 
-DOPENVDB_BUILD_BINARIES=OFF \
-DOPENVDB_BUILD_PYTHON_MODULE=OFF \ 
-DOPENVDB_BUILD_UNITTESTS=ON \ 
-DOPENEXR_ROOT=C:\tools\vcpkg\installed\x64-windows \ 
-DILMBASE_ROOT=C:\tools\vcpkg\installed\x64-windows \ 
-DTBB_ROOT=C:\tools\vcpkg\installed\x64-windows \ 
-DBLOSC_ROOT=C:\tools\vcpkg\installed\x64-windows \ 
-DUSE_BLOSC=ON \ 
-DCPPUNIT_ROOT=C:\tools\vcpkg\installed\x64-windows \ 
-DBOOST_ROOT=C:\Libraries\boost_1_67_0 \ 
-DBOOST_LIBRARYDIR=C:\Libraries\boost_1_67_0\lib64-msvc-14.0 \ ..
```

Let me know how you get on

**Comment by Danielhu229** [comment]
Followed by your advice, I managed to build it. However, the document I referenced in the first place -- README，may need some updates.
Thanks for helping me.

**Comment by ianww** [comment]
I'm trying to build openvdb against Houdini in Windows 10, using vcpkg (and then Visual Studio 2019).

I've run into the same error, which I haven't been able to resolve:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find IlmBase (missing: IlmBase_LIB_COMPONENTS Half) (found
  suitable version "2.2", minimum required is "2.2")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindIlmBase.cmake:285 (find_package_handle_standard_args)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
  openvdb/CMakeLists.txt:61 (find_package)
```

Firstly, it seems odd that it says "found suitable version" when it's also saying "could not find" it.

Also, inside C:\vcpkg\installed\x64-windows\lib I can see Half:

```
Half-2_3.lib
Half-s2_3_s.lib
```
So, it seems that it's there but CMake just can't find it.  I get the same error even if I explicitly point to this lib directory with my CMake command:

```
-DILMBASE_ROOT=”C:/vcpkg/installed/x64-windows/lib”
```

I've been making a guide document for myself as I go, which I've attached to show the detail of what I've done so far.
[OpenVDB installation using vcpkg - github query.pdf](https://github.com/AcademySoftwareFoundation/openvdb/files/4034772/OpenVDB.installation.using.vcpkg.-.github.query.pdf)

In summary, my steps have been:
```
.\vcpkg install --triplet x64-windows ilmbase blosc boost zlib openexr tbb boost-python cppunit 
.\vcpkg integrate install
```
If I run vcpkg list, it shows that ilmbase is installed:

```
ilmbase:x64-windows              2.3.0            empty package, linking to newer one
```
I've cloned the openvdb git:

```
git clone git@github.com:AcademySoftwareFoundation/openvdb.git
```
My CMake command in Windows Powershell is:

```
cmake `
-S"C:/vcpkg/openvdb" `
-G"Visual Studio 16 2019" `
-DOPENVDB_ABI_VERSION_NUMBER=5 `
-DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" `
-DHoudini_ROOT="C:/Program Files/Side Effects Software/Houdini 17.5.425" `
-DUSE_HOUDINI=ON `
-DOPENVDB_BUILD_HOUDINI_PLUGIN=ON `
-DUSE_DEFAULT_HOUDINI_INSTALL=ON `
-DOPENVDB_BUILD_PYTHON_MODULE=ON `
-DOPENVDB_BUILD_UNITTESTS=ON `
-DOPENEXR_ROOT="C:/vcpkg/installed/x64-windows" `
-DILMBASE_ROOT=”C:/vcpkg/installed/x64-windows/lib” `
-DTBB_ROOT="C:/vcpkg/installed/x64-windows" `
-DUSE_BLOSC=OFF `
-DCPPUNIT_ROOT="C:/vcpkg/installed/x64-windows" `
-DBOOST_ROOT="C:/vcpkg/installed/x64-windows" `
-DBOOST-PYTHON_ROOT="C:/vcpkg/installed/x64-windows" `
-DBOOST_LIBRARYDIR="C:/vcpkg/installed/x64-windows" `
-DZLIB_ROOT="C:/vcpkg/installed/x64-windows" `
..

```
I'm wondering if the error is because CMake is expecting to find Half in a discrete ilmbase libary but Half is now actually built inside OpenEXR, which the empty ilmbase package should be pointing to but isn't.

I'd really appreciate some guidance on resolving this!

**Comment by MaartentHart** [comment]
I ran into this problem. I got it fixed, but not the way I wanted to. I manually set the paths in [...]\openvdb\build\CMakeCache.txt

Such as:
IlmBase_INCLUDE_DIR:PATH=[...]\vcpkg\installed\x64-windows\include\OpenEXR

I had to do them one by one, untill it stopped complaining. It works now.

**Comment by Megidd** [comment]
I installed all dependencies with **vcpkg**:

https://github.com/AcademySoftwareFoundation/openvdb/tree/master#windows

However, I was receiving the same error:

> Could NOT find IlmBase (missing: IlmBase_INCLUDE_DIR IlmBase_LIB_COMPONENTS Half) (Required is at least version “2.2”)

But after adding these options to CMake the error got resolved: 

> -DCMAKE_TOOLCHAIN_FILE=C:/Users/m3/repos/vcpkg/scripts/buildsystems/vcpkg.cmake 

> -DVCPKG_TARGET_TRIPLET=x64-windows

I'm using JetBrains IDE, so I had to add CMake options here:

![2020-06-27 14_36_17-Movies   TV](https://user-images.githubusercontent.com/17475482/85920383-6eab3b00-b888-11ea-86b2-553a9772eeb8.png)
