### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by cjsb** [AcademySoftwareFoundation/openvdb#491]
Hi, I try to compile the code in Windows 10, but I getting the error.
![image](https://user-images.githubusercontent.com/12685275/61094280-804bc680-a41c-11e9-9ea0-8db56c21d170.png)

How do I solve this?

**Comment by halfjack** [comment]
I have the identical problem!

**Comment by cjsb** [comment]
I solved by adding the dependencies manually.
