### ISSUE TITLE
cannot find vdb_view

### ISSUE THREAD

**Issue by peiyunh** [AcademySoftwareFoundation/openvdb#519]
This might be a really dumb question. I just followed the cookbook and wrote my first hello world example. I am trying to visualize the result grid. It looks like I should find an executable named vdb_view. But somehow when I build & install openvdb, vdb_view was not compiled & installed along with vdb_print. Has anyone experienced this? Thanks!

OS: Ubuntu 18.04 
Version: 6.2.0

**Comment by peiyunh** [comment]
It seems like it was not enabled by default. Once I add `-DOPENVDB_BUILD_VDB_VIEW=ON` to cmake, it now builds vdb_view.

**Comment by jalovisko** [comment]
> It seems like it was not enabled by default. Once I add `-DOPENVDB_BUILD_VDB_VIEW=ON` to cmake, it now builds vdb_view.

My question might be dumber, but where should I add `-DOPENVDB_BUILD_VDB_VIEW=ON`?
