### ISSUE TITLE
Unable to find boost_python mac

### ISSUE THREAD

**Issue by rcallagh** [AcademySoftwareFoundation/openvdb#528]
I'm trying to build a standalone OpenVDB on macOS 10.14.5 but I keep running into the problem that cmake cannot find boost_python. I've copied the part of the CMake output where it fails when I used -DBoost_DEBUG=ON.

I can't figure out what is making this fail, I've followed the build instructions from the documentation and install boost and boost-python using homebrew but for some reason it's not finding boost_python. Any idea why this may be? 

```
-- ----------------------------------------------------
-- ------------ Configuring OpenVDBPython -------------
-- ----------------------------------------------------
-- Found Boost 1.71.0 at /usr/local/lib/cmake/Boost-1.71.0
--   Requested configuration: QUIET COMPONENTS python27
-- BoostConfig: find_package(boost_headers 1.71.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Found boost_headers 1.71.0 at /usr/local/lib/cmake/boost_headers-1.71.0
-- BoostConfig: find_package(boost_python 1.71.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- Found Boost 1.71.0 at /usr/local/lib/cmake/Boost-1.71.0
--   Requested configuration: QUIET COMPONENTS python
-- BoostConfig: find_package(boost_headers 1.71.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
-- BoostConfig: find_package(boost_python 1.71.0 EXACT CONFIG  QUIET HINTS /usr/local/lib/cmake)
CMake Error at openvdb/python/CMakeLists.txt:138 (message):
  Unable to find boost_python or boost_python27.
```

**Comment by Idclip** [comment]
Hello @rcallagh,

I believe this is an issue with newer versions of Boost's CMake configuration files. Can you please try adding `-D Boost_NO_BOOST_CMAKE=ON` to your cmake command (and ensuring you run said command in a fresh build directory). Let me know how that goes.

**Comment by Idclip** [comment]
Also, if you need it, python3 should now be supported as of PR #503

**Comment by rcallagh** [comment]
> Hello @rcallagh,
> 
> I believe this is an issue with newer versions of Boost's CMake configuration files. Can you please try adding `-D Boost_NO_BOOST_CMAKE=ON` to your cmake command (and ensuring you run said command in a fresh build directory). Let me know how that goes.

This worked perfectly, thanks!
