### ISSUE TITLE
Mac compilation error (ld: can't map file, errno=22 file)

### ISSUE THREAD

**Issue by YasinH** [AcademySoftwareFoundation/openvdb#543]
I'm having troubles compiling maya openvdb plugin on mac. I keep getting this error during make -j4

```
[ 98%] Building CXX object openvdb_maya/CMakeFiles/openvdb_maya.dir/OpenVDBWriteNode.cc.o
2 warnings generated.
[100%] Linking CXX shared library OpenVDB.bundle
ld: can't map file, errno=22 file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Foundation.framework' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [openvdb_maya/OpenVDB.bundle] Error 1
make[1]: *** [openvdb_maya/CMakeFiles/openvdb_maya.dir/all] Error 2
make: *** [all] Error 2
```
I'm on mac 10.14.6 and have xcode 11.1 
Can someone help with this?

**Comment by Idclip** [comment]
Hello @YasinH,
If I remember correctly, `System/Library/Frameworks/Foundation.framework` is a folder? Which I'm guessing is why you're seeing this error number. Something must be getting mixed up in our CMake. Could you please post the CMake command you're running and the terminal output?

Thanks

**Comment by YasinH** [comment]
I had actually managed to fix this. The problem was cmake was finding `System/Library/Frameworks/Foundation.framework` instead of Maya's  Maya_Foundation_LIBRARY=/Applications/Autodesk/maya2018/Maya.app/Contents/MacOS/libFoundation.dylib. After setting that directly in the cmake, it made it work.

**Comment by Idclip** [comment]
Marking as resolved
