### ISSUE TITLE
Problems in conversion mesh to level-set

### ISSUE THREAD

**Issue by marcomanno** [AcademySoftwareFoundation/openvdb#556]
Good Morning, I am experiencing problems converting meshes into level-set. 
I have checked all voxels and now I know that the distance field has occasionally the wrong sign and we have now two fixes (one is mine, and is precise wile a colleague has a patch for open_vdb code that fixes a bug but not the lack of precision).
My algorithm to test if a point is inside a mesh seems very reliable and fast, but it is not following the open_vdb coding standards (and I cannot spend time with that). 
The question is: is there someone available to take my code and integrate it into open_vdb?

**Comment by jmlait** [comment]
Thank you for your interest.   One approach would be to make a pull request with the code that doesn't match the coding standards.  In the pull request make it clear that you don't mind if we take it over and change it.

If the pull request passes the CLA/DCO tests, we could then take it over and finish it (provided we have time/interest, of course.  I can't make any statements about if we will accept it without seeing it)
