### ISSUE TITLE
Replace hard-coded multi-arch tuples in CMake

### ISSUE THREAD

**Issue by danrbailey** [AcademySoftwareFoundation/openvdb#611]
In CMake build system, swap out use of hard-coded multi-arch tuples such as:

`list(INSERT TBB_PATH_SUFFIXES 0 lib/x86_64-linux-gnu)`

with the LIBDIR variable:

`list(INSERT TBB_PATH_SUFFIXES 0 ${LIBDIR})`

These can be found in FindIlmBase, FindJemalloc, FindOpenEXR, FindTBB and the LIBDIR variable is set by CMake GNUInstallDirs (#498).

Full thread discussing this issue can be found here - #549

**Comment by Idclip** [comment]
https://github.com/AcademySoftwareFoundation/openvdb/pull/654

**Comment by Idclip** [comment]
Completed by #706 (subset of #654)
