### ISSUE TITLE
Use GEO_Detail::getBBox Instead of GEO_Detail::computeQuickBounds

### ISSUE THREAD

**Issue by danrbailey** [AcademySoftwareFoundation/openvdb#615]
Various SOPs use computeQuickBounds() instead of getBBox(). Convert them over to use the correct method to fix bounding issues. SOPs affected include Clip, Fill, Points Group, Rasterize Points, Read, Remove Divergence.

Full description of the issue by Jeff:

> GEO_Detail::computeQuickBounds is including the point of the VDB in the bounding box. computeQuickBounds, as its name suggests, tries to be quick. So it uses ALL points as its bounds and then enlarges by all primitives.
> 
> The GEO_Detail::getBBox(), by comparison, will call into computeQuickBounds if it is safe. But if there are any odd primitives, like packed primitives and VDB primitives, it will instead compute the bounding box of all the primiitves; and then add any unused points. Since the origin of the VDB isn't unused, it won't be contained.
> 
> Long story short: use getBBox(). It should be just as fast for simple cases, and will handle VDBs/Packed Prims properly.

**Comment by saepenumero** [comment]
Hi, may I work on this issue?

**Comment by Idclip** [comment]
Currently in progress by @kubaroth

**Comment by Idclip** [comment]
Resolved by #702
