### ISSUE TITLE
Make ZLib an Optional Dependency

### ISSUE THREAD

**Issue by danrbailey** [AcademySoftwareFoundation/openvdb#618]
Modelled on OPENVDB_USE_BLOSC, it would be nice to introduce OPENVDB_USE_ZLIB that could be used to make the zlib compression library an optional dependency.

This should be added to the core library, the CMake build system and the OpenVDB Read SOP and should default to ON.

**Comment by shixianli158** [comment]
very good

**Comment by Idclip** [comment]
Resolved as of https://github.com/AcademySoftwareFoundation/openvdb/pull/817
