### ISSUE TITLE
Don't require the python interpreter in openvdb/python when unit tests are disabled

### ISSUE THREAD

**Issue by e4lam** [AcademySoftwareFoundation/openvdb#621]
In trying to build the openvdb python module for vcpkg, I ran into a problem with openvdb/python requiring the python interpreter even when unit tests are disabled. By default, the openvdb vcpkg doesn't build unit tests and so it doesn't have a dependency that provides the python interpreter. Since I didn't want to add an extraneous dependency just for building I just patched it to remove this requirement. However, I think a worthwhile improvement here is to only require the python interpreter when the option `OPENVDB_BUILD_UNITTESTS` is enabled.

I encountered this while trying to help out issue #603.

**Comment by danrbailey** [comment]
I agree, I think this is a good suggestion, thanks @e4lam. I'm going to mark this as a good first issue as it doesn't seem too challenging to implement.

**Comment by Idclip** [comment]
I'll be looking as this as part of the some upcoming windows improvements

**Comment by Idclip** [comment]
https://github.com/AcademySoftwareFoundation/openvdb/pull/646

**Comment by Idclip** [comment]
Fixed as of #646

**Comment by e4lam** [comment]
Thanks!
