### ISSUE TITLE
Cannot build pyopenvdb with numpy

### ISSUE THREAD

**Issue by theNewFlesh** [AcademySoftwareFoundation/openvdb#662]
I am trying to build pyopenvdb for a python3.7 environment that uses numpy.

I have an ubuntu 19.04 docker container with a bunch of deps installed and a custom Makefile. It is just a copy of the one that comes with the repo but with the XXX_LIB_DIR and XXX_INCL_DIR variables pointed to the right places.

I have gotten it to work without numpy in my docker repo here:
https://github.com/theNewFlesh/docker_pyopenvdb

Trying to get it to work has been utterly miserable.
It will build, but when I run `import pyopenvdb` inside python3.7, I get this:
`ImportError: /root/openvdb/openvdb/pyopenvdb.so: undefined symbol: _ZN5boost6python5numpy6detail15get_float_dtypeILi32EEENS1_5dtypeEv`

Any suggestions on what I should try?

**Comment by theNewFlesh** [comment]
Fixed that issue only to run into this:
`RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
ImportError: numpy.core._multiarray_umath failed to import`

**Comment by danrbailey** [comment]
Hi Alex, this is a known issue, see this section of the dependency documentation:

https://www.openvdb.org/documentation/doxygen/dependencies.html#depKnownIssues

**Comment by theNewFlesh** [comment]
Thanks for the info, I built boost from source and now pyopenvdb works with numpy.

**Comment by petulka8s** [comment]
Hi,
do you know if there is a way how to do that for Windows?
I have the same issue with boost-numpy.

**Comment by theNewFlesh** [comment]
I don’t know.
