### ISSUE TITLE
Quaternion inverse is not const

### ISSUE THREAD

**Issue by mtao** [AcademySoftwareFoundation/openvdb#669]
Is there a strong reason for why Quat::inverse is not labelled const?

https://github.com/AcademySoftwareFoundation/openvdb/blob/f8d318581635a2c90c1924aa9973e1ae8a4d9d7f/openvdb/math/Quat.h#L505

**Comment by Idclip** [comment]
Hi @mtao - It doesn't look like it! Feel free to open up a PR, otherwise I'm sure someone will fix this soon

**Comment by Idclip** [comment]
Closing as completed, thanks for the contribution
