### ISSUE TITLE
Unable to build vdb_view binary on Windows

### ISSUE THREAD

**Issue by KartikShrivastava** [AcademySoftwareFoundation/openvdb#677]
While generating project files with cmake on Windows, I received following warning and vdb_view project wasn't created in visual studio 2017 solution file.

> CMake Warning at openvdb/cmd/CMakeLists.txt:172 (message):
>   Currently no CMake support for building vdb_view binary on Windows.

**Comment by KartikShrivastava** [comment]
After installing the `glfw3` using `vcpkg install zlib:x64-windows`, I've edited the line  171 of `openvdb\cmd\CMakeLists.txt` by inverting the `if` condition and now CMake is able to generate `vdb_viewer` project. But I'm still not sure about the purpose of that if statement.
>  if(NOT WIN32)   #Previously it was if(WIN32)
    message(WARNING "Currently no CMake support for building vdb_view binary on Windows.")
    # @todo
    # find_package(GLEW REQUIRED)
    ...

**Comment by Idclip** [comment]
The purpose of that if statement is to disable the project on Windows as the code will not compile/run. Please see https://github.com/AcademySoftwareFoundation/openvdb/pull/671

**Comment by Idclip** [comment]
Merged, #671 vdb_view now builds and runs on Windows with GLEW. Please re-open if problems persist
