### ISSUE TITLE
OpenVDB does not compile with GCC 6.1.1

### ISSUE THREAD

**Issue by malaterre** [AcademySoftwareFoundation/openvdb#70]
Relevant log:

Relevant part (hopefully):

> g++ -c -DOPENVDB_PRIVATE -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fvisibility=hidden -fvisibility-inlines-hidden -pthread -g -I . -I .. -isystem /usr/include -isystem /usr/include/OpenEXR -isystem /usr/include -isystem /usr/include -isystem /usr/include -DOPENVDB_USE_BLOSC -DOPENVDB_USE_LOG4CPLUS -DOPENVDB_USE_GLFW_3 -fPIC -o Grid.o Grid.cc
> In file included from /usr/include/c++/6/ext/string_conversions.h:41:0,
>                  from /usr/include/c++/6/bits/basic_string.h:5402,
>                  from /usr/include/c++/6/string:52,
>                  from /usr/include/c++/6/bits/locale_classes.h:40,
>                  from /usr/include/c++/6/bits/ios_base.h:41,
>                  from /usr/include/c++/6/ios:42,
>                  from /usr/include/c++/6/ostream:38,
>                  from /usr/include/c++/6/iostream:39,
>                  from Grid.h:34,
>                  from Grid.cc:31:
> /usr/include/c++/6/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
>  #include_next <stdlib.h>
>                          ^
> compilation terminated.
> make[2]: **\* [Grid.o] Error 1

**Comment by malaterre** [comment]
The issue is given in details at: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70129

**Comment by malaterre** [comment]
Proper fix would be to avoid using '-isystem /usr/include' in the Makefiles

**Comment by aditiapratama** [comment]
hi @malaterre, have you succeed build it using gcc 6.1.1?  any workaround? I don't know how to fix it by avoid using `-isystem /usr/include`

**Comment by aditiapratama** [comment]
Okay, avoiding use `/usr/include` did the trick for me but still fail when building `vdb_print`, etc. Here's the log

```bash
make lib install
make: Nothing to be done for 'lib'.
Building vdb_print because of libopenvdb.so.3.2.0 main.cc
g++ -std=c++0x -pthread -O3 -DNDEBUG -I . -I .. -isystem /usr/include/boost -isystem /opt/lib/openexr/include -isystem /usr/include/tbb -isystem /opt/lib/blosc/include -isystem /usr/include/log4cplus -DOPENVDB_USE_BLOSC -DOPENVDB_USE_LOG4CPLUS -DOPENVDB_USE_GLFW_3 -o vdb_print cmd/openvdb_print/main.cc -I . \
    -Wl,-rpath,/opt/lib/openvdb/lib -L/home/aditia/src/blender-deps/openvdb-master/openvdb libopenvdb.so.3.2.0 \
    -ldl -lm -lz -Wl,-rpath,/opt/lib/openexr/lib -L/opt/lib/openexr/lib -lHalf -Wl,-rpath,/usr/lib64 -L/usr/lib64 -ltbb -Wl,-rpath,/usr/lib64 -L/usr/lib64 -lboost_iostreams -lboost_system  -Wl,-rpath,/opt/lib/blosc/lib -L/opt/lib/blosc/lib -lblosc -lz -Wl,-rpath,/usr/lib64 -L/usr/lib64 -llog4cplus -Wl,-rpath,/usr/lib64 -L/usr/lib64 -lrt -ljemalloc
/usr/bin/ld: vdb_print: hidden symbol `__cpu_model' in /usr/lib/gcc/x86_64-redhat-linux/6.1.1/libgcc.a(cpuinfo.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:735: recipe for target 'vdb_print' failed
make: *** [vdb_print] Error 1
```

**Comment by phcerdan** [comment]
This is a duplicate of #144

In short:
Set CMake option to not use isystem for imported targets:

```
cmake ../src -DCMAKE_NO_SYSTEM_FROM_IMPORTED:BOOL=TRUE 
```

**Comment by malaterre** [comment]
Just for reference, the original post was using the Makefile based build system. I'll switch to cmake for Debian package. Thanks for help !
