### ISSUE TITLE
Downloading test data fails

### ISSUE THREAD

**Issue by blezek** [AcademySoftwareFoundation/openvdb#716]
From the [download page on the website](https://www.openvdb.org/download/) I can not download any of the sample models such as the [armadillo.vdb](https://artifacts.aswf.io/releases/io/aswf/openvdb/models/armadillo.vdb/1.0.0/armadillo.vdb-1.0.0.zip).  The error message is:

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
releases/io/aswf/openvdb/models/armadillo.vdb/1.0.0/armadillo.vdb-1.0.0.zip
</Key>
<RequestId>C13281DD73D8E125</RequestId>
<HostId>
pFPxssALt+v4bL3FjyU+cdyP9FcjXePhmMiZhUOtjeLaB7/7sFIx4KhmCnJxt6uNfeckSQiHOcg=
</HostId>
</Error>
```

Can the links be fixed or can you provide an alternative download location?

**Comment by danrbailey** [comment]
Apologies for the inconvenience, we’re aware of this issue and are looking into it.

**Comment by Idclip** [comment]
The following PR should resolve this:

https://github.com/AcademySoftwareFoundation/openvdb-website/pull/24

**Comment by cesarvspr** [comment]
it didnt work for me. Can you say what exactly i should do please?

**Comment by danrbailey** [comment]
This has now been resolved and the download links should work again. Thanks for your patience.

**Comment by cesarvspr** [comment]
Hey Dan, I  did the standalone installation, whats is the command that I need to do to run a .vdb file?
