### ISSUE TITLE
CONCURRENT_MALLOC default should be None

### ISSUE THREAD

**Issue by lgritz** [AcademySoftwareFoundation/openvdb#742]
I've run into multiple user site issues resulting from the default build of OpenVDB replacing the process malloc wholesale with jemalloc by default. This will not only change the allocations made by OpenVDB itself, but it will affect the whole of any application or library that links to it.

As an example, since OpenImageIO links against OpenVDB (it can read vdb files as volumetric texture), that means that OIIO gets jemalloc whether it wants it or not. OSL links against OIIO (to use its texture system, among other things), so OSL in turn gets jemalloc whether it wants it or not. And any application that links against OSL -- even if it doesn't use OpenVDB, even if it's not even aware or planning for OpenVDB's existence at all -- will end up with jemalloc. That may thwart or conflict with other malloc strategies that the app intended to use, may conflict with other libraries also used by the same app, and may do so in very subtle ways including having the particular malloc of all the components depend on the exact link or LD_LIBRARY_PATH order.

I would like to suggest that proper library etiquette is that pure libraries should never link against a malloc replacement library (certainly not by default). Top level apps should make a decision about which library they want and impose that on its libraries, not the other way around. Command line tools that are part of OpenVDB are fine to link against an alternate malloc, and it's certainly fine to document and strongly suggest that apps linking against OpenVDB's libraries use jemalloc for optimal OpenVDB performance. But I don't believe the openvdb library should do it preemptively and out of the control of the application.

I admit that my request is also not fully satisfactory -- I totally get where you're coming from, wanting the default choice to be the one that gives optimal OpenVDB performance and memory use. Maybe there is another way to skin this cat, but so far on my end, the way it stands now has been repeated trouble. And for what it's worth, many of our applications, including our renderer, DO link jemalloc in the end... but it's not always helpful for libraries to make it mandatory. For example, we may simply want a different jemalloc version than OpenVDB found, or we may want to be easily able to experiment and benchmark alternatives.

**Comment by kmuseth** [comment]
Good timing, we'll discuss it tomorrow at our TSC meeting - you're welcome
to join!

**Comment by lgritz** [comment]
Yes, I'll try to attend, thanks!

**Comment by lgritz** [comment]
Summary of TSC consensus as best as I can remember (please feel free to correct or amend):

0. This problem has been reported a lot, and it's especially problematic when jemalloc is introduced to a process after initial launch, for example by a dynamically loaded plugin that has linked against an OpenVDB that pulls in jemalloc. (Example case: Python loading a module that has a dependency on OpenVDB.)

1. The default build of the OpenVDB library itself should not link in a malloc replacement. (jemalloc is easy to add, but hard to take away once it's a link dependency of libopenvdb)

2. The exported CMake config files should provide two targets: one with just the core openvdb library, and a second target that is openvdb + jemalloc (or whatever malloc replacement is preferred). Downstream apps or libraries can choose the one appropriate for their situation.

3. Also under consideration? -- some kind of runtime check to warn users that no malloc replacement is detected, so openvdb is not performing as well as it could.

**Comment by lgritz** [comment]
Side comment for Jeff Lait: In our in-house renderer, we're currently using jemalloc 4.5. We recently tested jemalloc 5.2 and found it used about 15% more memory than 4.5. All of jemalloc (both versions), tbbmalloc, mimalloc, and tcmalloc were superior to the system allocator, but jemalloc 4.5 is the best balance of time and memory for our use case. It's easy to imagine that the best choice among those is dependent on your particular allocation pattern and needs, so you should do a similar multi-way test on your use case.

**Comment by Idclip** [comment]
https://github.com/AcademySoftwareFoundation/openvdb/pull/749

**Comment by e4lam** [comment]
This issue can be closed?

**Comment by Idclip** [comment]
Yes this has now been merged!
