### ISSUE TITLE
Debug builds link release versions of libraries on Windows

### ISSUE THREAD

**Issue by matthewdcong** [AcademySoftwareFoundation/openvdb#753]
Debug builds of OpenVDB appear to be linking to release versions of IlmBase, OpenEXR, and TBB on Windows. In certain cases, this works as far as I can tell. However, this can fail in the following ways when statically linking:

1. On Windows, if you specify the MSVC Runtime Library when statically linking (using the functionality added in #708, thank you!), you can run into conflicts between the debug and release builds. For example, if OpenVDB is compiled with the debug version of the runtime and OpenEXR is compiled with the non-debug and debug versions of the runtime for the release and debug version respectively, linking against the release version will fail due to a runtime mismatch.

2. Disabling autolinking for TBB appears to only be handled correctly for release builds. In FindTBB.cmake, we also need to define `__TBB_NO_IMPLICIT_LINKAGE=1` if the library name is `tbb_debug`. However, this is not sufficient because OpenVDB only currently searches for the release version of the libraries and does not include `tbb_debug` as a possible library name. Even if this appears to link correctly during the build, it can often fail when you try to link the OpenVDB library from another application where it complains that `tbb_debug` cannot be found (because `tbb` has been (incorrectly) statically linked into `libopenvdb.lib` and `tbb_debug` is still expected to be autolinked).

I think the correct way to handle this would be to extend the OpenVDB CMake modules to set both release and debug versions of the library variables. Then, the main CMakeLists.txt file can choose between these based on the `CMAKE_BUILD_TYPE`.

**Comment by Idclip** [comment]
Hey @matthewdcong thanks for the detailed description, I completely agree with your analysis and proposed solution. A few extra things that need to be considered:

 - It may be that tbb is not the only library to rename itself in this way for debug builds - although there is no single standard filename convention for debug builds, it's not unexpected for libs to suffix themselves with 'd' or the like. I've mentioned this in other threads, but ideally we should be dropping our find modules in favour of the new config scripts deployed with tbb. I'm just not entirely sure if the minimum version of tbb we need to support has acceptable cmake to rely on.
 - Whilst fixing our find modules to find debug variants of deps is part of the solution, a full solution would require support for CMake multi-configuration in OpenVDB itself (as you've suggested). This would mean being able to configure Debug, RelWithDebInfo, MinSizeRel and Release variants of each library/executable in a single run of CMake. There's a good thread here which touches on a lot of the challenges of doing this, albeit in a slightly different context https://github.com/conan-io/conan/issues/330.

I propose that, in the short term, we simply add "correct" behaviour for `-DCMAKE_BUILD_TYPE=Debug` which switches to different expected dep names. This isn't really the right thing to do as msvc will go ahead and generate all 4 targets anyway, but so long as the single Debug build is correctly configured you would be able to execute a Release and Debug build in two runs of CMake. 

I also wonder if there's a use case of building just OpenVDB with `-g` ? It seems reasonable to assume that you may only care about vdb symbols and want to link against release variants of dependencies. I'm not sure how to achieve this behaviour with the standard CMake configurations.

**Comment by matthewdcong** [comment]
Thanks Nick, I tried your workaround for adding the "correct" behavior for `-DCMAKE_BUILD_TYPE=Debug` and that allowed me to get past the aforementioned issues.

I agree with all of your points above -- a full solution has a lot of challenges. This is by no means a complete solution but what if we extend `FindTBB.cmake` to return `TBB_LIBRARIES_RELEASE` and `TBB_LIBRARIES_DEBUG` instead of the current `TBB_LIBRARIES` and then call `target_link_libraries(optimized ${TBB_LIBRARIES_RELEASE} debug ${TBB_LIBRARIES_DEBUG})` *and repeat this for OpenEXR and IlmBase)? It wouldn't handle all of the potential locations but I think it would go a long ways towards enabling multi-configuration support. I believe anything that doesn't classify as a debug configuration falls back to the optimized optimized configuration (i.e. the current behavior). Quite possible I missed some subtlety and this idea just doesn't work though.

**Comment by Idclip** [comment]
Hey @matthewdcong, I found some time to look into this and have linked a PR which attempts to add support for this behaviour.

**Comment by matthewdcong** [comment]
Thank you @Idclip! I read through the changes and they look good to me. Thanks for taking this on -- it'll be super helpful!
