### ISSUE TITLE
external const definition moved to headers?

### ISSUE THREAD

**Issue by cgolchert** [AcademySoftwareFoundation/openvdb#773]
Is there a reason why INVALID_IDX and COORD_OFFSETS are not defined in the header?

util.h:
```
OPENVDB_API extern const Index32 INVALID_IDX;

/// @brief coordinate offset table for neighboring voxels
OPENVDB_API extern const Coord COORD_OFFSETS[26];
```

Why do we need a .cc file for just "const Index32 INVALID_IDX = std::numeric_limits<Index32>::max();" and a handful of coords?

I have seen linking errors since v5 because it wasn't seeing util.cc for some reason.

**Comment by Idclip** [comment]
This has inadvertedly been solved with #1620
