### ISSUE TITLE
TBB CMAKE configuration

### ISSUE THREAD

**Issue by TylerGubala** [AcademySoftwareFoundation/openvdb#784]
**OS**: Centos 7

Hi, I am trying to build `manylinux` compatible `wheel` files to distribute Blender built as a Python module.

Currently, I am having a great deal of trouble setting up my CI to build OpenVDB the proper way.

Part of the issue is that `manylinux` depends partly on the premise that building a `wheel` file on a very old version of linux would allow users to install the very old libraries since the "OS" libraries would theoretically be compatible, due to backwards compatibility.

I am using a Docker image based on a CentOS circa 2014 because of this concept. This means that the TBB available for this CentOS is only version 4.

OpenVDB is looking for something newer than TBB 2017, so I have downloaded the latest linux zip.

I extracted the TBB zipfile into the directory suggested by the TBB website, which is `/opt/intel`

However, OpenVDB still was having trouble finding TBB, so I started trying to set the TBB cmake variables, but it is still giving me an error about the TBB variables.

**In my build script**

``` bash
mkdir /opt/intel
cd /opt/intel
curl -L https://github.com/oneapi-src/oneTBB/releases/download/v2020.3/tbb-2020.3-lin.tgz -o tbb-2020.3-lin.tgz
tar xzf tbb-2020.3-lin.tgz
cd ~

git clone https://github.com/AcademySoftwareFoundation/openvdb.git
cd openvdb
mkdir build
cd build
cmake .. -DTBB_LIBRARY_DIR=/opt/intel/tbb/lib/intel64/gcc4.8 -DTbb_INCLUDE_DIR=/opt/intel/tbb/include/tbb -DTbb_LIB_COMPONENTS=/opt/intel/tbb/lib/intel64/gcc4.8/libtbb.so -Dtbb=/opt/intel/tbb/lib/intel64/gcc4.8/libtbb.so >> openvdb_install.log
make -s >> openvdb_install.log
make install -s >> openvdb_install.log
cd ../..

```

**Error**

```
mkdir /opt/intel
+ cd /opt/intel
+ curl -L https://github.com/oneapi-src/oneTBB/releases/download/v2020.3/tbb-2020.3-lin.tgz -o tbb-2020.3-lin.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   629  100   629    0     0   2181      0 --:--:-- --:--:-- --:--:--  2184
100 8565k  100 8565k    0     0  15.9M      0 --:--:-- --:--:-- --:--:-- 15.9M
+ tar xzf tbb-2020.3-lin.tgz
+ cd /root
+ git clone https://github.com/AcademySoftwareFoundation/openvdb.git
Cloning into 'openvdb'...
+ cd openvdb
+ mkdir build
+ cd build
+ cmake .. -DTBB_LIBRARY_DIR=/opt/intel/tbb/lib/intel64/gcc4.8 -DTbb_INCLUDE_DIR=/opt/intel/tbb/include/tbb -DTbb_LIB_COMPONENTS=/opt/intel/tbb/lib/intel64/gcc4.8/libtbb.so -Dtbb=/opt/intel/tbb/lib/intel64/gcc4.8/libtbb.so
CMake Error at /cmake-3.17.3-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find TBB (missing: Tbb_LIB_COMPONENTS) (Required is at least
  version "2017.0")
```

**Comment by Idclip** [comment]
Hi @TylerGubala, try the following:
```
cmake .. -DTBB_LIBRARYDIR=/opt/intel/tbb/lib/intel64/gcc4.8 -DTBB_INCLUDEDIR=/opt/intel/tbb/include
```
Note the subtle differences in the cmake var names and the path to include, not include/tbb. Let me know how that goes.

**Comment by TylerGubala** [comment]
@Idclip Thank you, that resolved that error,

However now I have an issue with specifying the `BOOST_ROOT` variable, since boost is way out of date for CentOS 7.

**In my build script**

```bash

mkdir /opt/intel
cd /opt/intel
curl -L https://github.com/oneapi-src/oneTBB/releases/download/v2020.3/tbb-2020.3-lin.tgz -o tbb-2020.3-lin.tgz
tar xzf tbb-2020.3-lin.tgz
cd ~

mkdir boost
curl -L https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0_rc1.tar.gz -o boost_1_74_0_rc1.tar.gz
tar xzf boost_1_74_0_rc1.tar.gz
cd ..

git clone https://github.com/AcademySoftwareFoundation/openvdb.git
cd openvdb
mkdir build
cd build
cmake .. -DBOOST_ROOT=../boost -DTBB_LIBRARYDIR=/opt/intel/tbb/lib/intel64/gcc4.8 -DTBB_INCLUDEDIR=/opt/intel/tbb/include >> openvdb_install.log
make -s >> openvdb_install.log
make install -s >> openvdb_install.log
cd ../..
```

**Error**

```bash
+ cmake .. -DBOOST_ROOT=../boost -DTBB_LIBRARYDIR=/opt/intel/tbb/lib/intel64/gcc4.8 -DTBB_INCLUDEDIR=/opt/intel/tbb/include
CMake Warning at openvdb/CMakeLists.txt:89 (message):
  The version of Blosc located is greater than 1.5.0.  There have been
  reported issues with using later versions of Blosc with OpenVDB.  OpenVDB
  has been tested fully against Blosc 1.5.0, it is recommended that you use
  this version where possible.
CMake Error at /cmake-3.17.3-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost: Found unsuitable version "1.53.0", but required is at
  least "1.61" (found /usr/include)
Call Stack (most recent call first):
  /cmake-3.17.3-Linux-x86_64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:443 (_FPHSA_FAILURE_MESSAGE)
  /cmake-3.17.3-Linux-x86_64/share/cmake-3.17/Modules/FindBoost.cmake:2166 (find_package_handle_standard_args)
  openvdb/CMakeLists.txt:111 (find_package)
```

`BOOST_ROOT` is mentioned in the `build.txt` and on OpenVDB's site but I can't find it in `CMakeLists`; was it removed?

**Comment by Idclip** [comment]
You could try this: https://github.com/actions/virtual-environments/issues/687#issuecomment-610471671

something like:
```
  -DBOOST_ROOT=../boost -DBOOST_INCLUDEDIR=../boost/boost/include -DBOOST_LIBRARYDIR=../boost/lib
```

depending on the contents of that tar. Not sure if the relative path might cause an issue too.

> BOOST_ROOT is mentioned in the build.txt and on OpenVDB's site but I can't find it in CMakeLists; was it removed?

vdb doesn't do anything with the Boost CMake vars, they should be respected by CMake itself

**Comment by TylerGubala** [comment]
> vdb doesn't do anything with the Boost CMake vars, they should be respected by CMake itself

That goes to show how much I know about CMake!

Thank you much for your help; those boost variables were not needed. I just needed to follow `boost` documentation and perform `./bootstrap.sh` followed by `./b2 install` for the CMake build chain to recognize it. 

OpenVDB is building excellently now, thanks again!
