### ISSUE TITLE
[CMake] Windows static build LNK2001

### ISSUE THREAD

**Issue by diiigle** [AcademySoftwareFoundation/openvdb#821]
If you're building openvdb as a static library on Windows, you need to define `OPENVDB_STATICLIB` to circumvent the following definition of `OPENVDB_DLL`:
https://github.com/AcademySoftwareFoundation/openvdb/blob/e4daaad54338c0d36171d88eca394bda92cf67d2/openvdb/openvdb/PlatformConfig.h#L14

Else it will cause errors like these:
`
Error	LNK2001	unresolved external symbol "__declspec(dllimport) int __cdecl openvdb::v7_1::util::printBytes(class std::basic_ostream<char,struct std::char_traits<char> > &,unsigned __int64,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool,int,int)" (__imp_?printBytes@util@v7_1@openvdb@@YAHAEAV?$basic_ostream@DU?$char_traits@D@std@@@std@@_KAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@5@2_NHH@Z) `

Shouldn't CMake take care of this and add it to the PUBLIC defines of the target?
https://github.com/AcademySoftwareFoundation/openvdb/blob/064606e7ae04fc3c651f86714c28853517a2f72b/openvdb/openvdb/CMakeLists.txt#L425-L447

**Comment by Idclip** [comment]
Hey @diiigle, I believe you're correct - it currently assumes that specifying `/MD` or `/MDd` alone is enough to infer the lib type which is not true. 

This header existed pre CMake - I'm wondering if we can't now remove this logic as it is a bit weird (and the shared builds already correctly specify `OPENVDB_DLL`) though this would break downstream projects who are linking dynamically against VDB and relying on this behaviour without specifying `-DOPENVDB_DLL`...

Simplest solution is, as you say, to add that define to the static build.

**Comment by Idclip** [comment]
https://github.com/AcademySoftwareFoundation/openvdb/pull/826

**Comment by Idclip** [comment]
Thanks again for reporting @diiigle, this change has been merged
