### ISSUE TITLE
NanoVDB Ray intersects with an empty BBox not working correctly

### ISSUE THREAD

**Issue by mbreitzke** [AcademySoftwareFoundation/openvdb#833]
in the nanvodb Ray class the intersection does not check for an empty bbox. This will result in wrong results. In the examples provided the

if (!ray.clip(acc.root().bbox())) {
        return Vec3f(0.0f);
    }

for example will not work. While this is easy to workaround, it would be checked I think (similar like #469 I think)

**Comment by kmuseth** [comment]
Thanks for pointing this out - I've fixed this issue and plan to merge it later this week
