### ISSUE TITLE
NanoVDB Grid worldToIndexDirF / indexToWorldDirF problem ?

### ISSUE THREAD

**Issue by mbreitzke** [AcademySoftwareFoundation/openvdb#834]
In the Grid class the functions to transform a direction are not working correctly. 
While in transforming a point with worldToIndexF the matF in struct Map is used, the transforming of the direction uses the inverse mInvMatF. When a ray is transformed with ray.worldToIndexF(grid); this results in a wrong transformation. I see that the working code is commented out. Is there any reason why it's changed? but in my code it results in a wrong ray transformation. 
I can workaround this easily for now but it should be checked

**Comment by webanck** [comment]
I tracked a bug all the day to end on the same issue : `Ray::worldToIndexFirF` is erroneous because the ray direction is transformed with `applyJacobianF` instead of `applyInverseJacobianF`.

**Comment by webanck** [comment]
This issue seems closed to me, isn't it ?

**Comment by kmuseth** [comment]
yes I added the fix to feature/nanovdb a few weeks ago but forgot to close this ticket
