### ISSUE TITLE
NanoVDB nvdb file metadata retro-compatibility

### ISSUE THREAD

**Issue by webanck** [AcademySoftwareFoundation/openvdb#836]
Hello, I converted some OpenVDB volume to NanoVDB using `nanovdb_convert` built from commit 64adc5a (23 August).
I upgraded today to the latest commit but when reading the volume file, I got an error about the GridMetadata.
So I reconverted from the OpenVDB volume to a new NanoVDB one and it seems to work.

Is this non retro-compatibility the expected behavior ?

**Comment by kmuseth** [comment]
Please pull the latest change from feature/nanovdb - I fixed a bug where the major file number was not correctly checked for. Now you should get meaning full error messages if you;re trying to open an old .nvdb with a newer version. Unfortunately I cannot implement backwards comparability yet - that will be added once nanovdb make it into the master branch. However, I believe the memory/file-format has stabilized and I have no plans/expectations that it will change any time soon (though I obviously cannot guarantee that it wont)

**Comment by kmuseth** [comment]
Also use the two following command-line tools:

1) nanovdb_print which can print useful information about nvdb files - including it's version number

2) nanovdb_validate which will change and validate an nvdb file for possible corruption

**Comment by webanck** [comment]
This time, converting an OpenVDB file to NanoVDB format and trying to read it with the same revision outputs an error:
```
Incompatible file format: The file is written in an older version of NanoVDB: 27.0.X!
	Recommendation: Re-generate this NanoVDB file with the never version 28.X of NanoVDB
```
