### ISSUE TITLE
cannot get libboost_python37.so.1.68.0 to make pyopenvb work (Python 3.8.3, Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by andrewrgarcia** [AcademySoftwareFoundation/openvdb#845]
After installing all dependencies and building OpenVDB from https://github.com/AcademySoftwareFoundation/openvdb, I ran TestOpenVDB.py and got the following message:

**libboost_python37.so.1.68.0: cannot open shared object file: No such file or directory**

I ran "apt-file search libboost_python" in the Terminal to make sure the package was nowhere in my computer and it was not. 
I then ran an extensive "aptitude search boost 1.68" search in the Terminal and the closest named file to the requirement was **lib64boost-python37-1.68.0**. I installed it and then ran the TestOpenVDB.py file again but it still gave me the same message, seeing as it is not the same file. I did extensive searches of lib64 and libboost with the 1.68 1.67 and 1.71 extension and I could not find the elusive **libboost_python37.so.1.68.0** which python is asking for. 

I am running Ubuntu 20.04 and Python 3.8.3, which are currently the most updated versions. Please help with this difficult issue, I would sincerely appreciate it. It is likely that I am not the only person with this problem right now. 

Sincerely,
Andrew

**Comment by andrewrgarcia** [comment]
wanted to follow up. I have also installed pyopenvdb in python3.7 as I thought it may have been a version issue, but still got the same message i.e. **libboost_python37.so.1.68.0: cannot open shared object file: No such file or directory**

**Comment by Idclip** [comment]
Hi @andrewrgarcia are you still running into this issue? If so could you post the output you get when running `cmake`? Verbose build output (i.e. `make VERBOSE=1`) would be useful too. Thanks

**Comment by andrewrgarcia** [comment]
> Hi @andrewrgarcia are you still running into this issue? If so could you post the output you get when running `cmake`? Verbose build output (i.e. `make VERBOSE=1`) would be useful too. Thanks

Hello Nick,

Yes I am still running into the issue. Below are the verbose outputs I get for **make** and **make install**, respectively.

-Andrew
[output_make.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5569455/output_make.txt)
[output_makeinstall.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5569456/output_makeinstall.txt)

**Comment by Idclip** [comment]
Thanks @andrewrgarcia however I can't see the build output for the OpenVDB Python project in the files you've uploaded. Could you provide the verbose make output for that too? 

Are you using CMake to generate the makefiles? If so, could you provide that output as well? Specifically I'm interested in what CMake reports it's finding for dependencies during configuration (make sure the python lib is enabled with `-OPENVDB_BUILD_PYTHON_MODULE=ON`)

**Comment by andrewrgarcia** [comment]
> Thanks @andrewrgarcia however I can't see the build output for the OpenVDB Python project in the files you've uploaded. Could you provide the verbose make output for that too?
> 
> Are you using CMake to generate the makefiles? If so, could you provide that output as well? Specifically I'm interested in what CMake reports it's finding for dependencies during configuration (make sure the python lib is enabled with
> `-DOPENVDB_BUILD_PYTHON_MODULE=ON`)

Hi, 
what do you mean by "the build output for the OpenVDB Python project"? Here is the cmake out

[out_cmake.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5569631/out_cmake.txt)

**Comment by Idclip** [comment]
The OpenVDB repo CMake build system has flags for enabling/disabling different build components. They are listed here: https://www.openvdb.org/documentation/doxygen/build.html#buildComponents

The output from your CMake tells me you're not enabling the pyopenvdb library component - so thats not being built when you're running `make`. When running `cmake` for the first time in the VDB repo you can specify which projects to enable. By default only the core library and vdb_print binary are enabled. To create a valid make target for `pyopenvdb` you need to add `-DOPENVDB_BUILD_PYTHON_MODULE=ON` to your `cmake` command. When you then run `make install` the OpenVDB Python lib will be built.

Interestingly, even though you're not installing it, it seems that `pyopenvdb` may exist somewhere on your system, otherwise you'd get and error trying to run `python TestOpenVDB.py` with something like `ImportError: No module named pyopenvdb` ... so I'm not sure what's going on there...

**Comment by andrewrgarcia** [comment]
Oh, 

where exactly hould I add DOPENVDB_BUILD_PYTHON_MODULE=ON in CMakeLists.txt?

**Comment by Idclip** [comment]
If you're invoking `cmake` from the command line you simple add it to your command. For example:
```
cmake -DOPENVDB_BUILD_PYTHON_MODULE=ON ..
```
Otherwise, in the root `CMakeLists.txt` file, you can change:

```
option(OPENVDB_BUILD_PYTHON_MODULE "Build the pyopenvdb Python module" OFF)
```
to
```
option(OPENVDB_BUILD_PYTHON_MODULE "Build the pyopenvdb Python module" ON)
```

**Comment by andrewrgarcia** [comment]
Hi, 
I still get the 

> If you're invoking `cmake` from the command line you simply add it to your command. For example:
> 
> ```
> cmake -DOPENVDB_BUILD_PYTHON_MODULE=ON ..
> ```
> 
> Otherwise, in the root `CMakeLists.txt` file, you can change:
> 
> ```
> option(OPENVDB_BUILD_PYTHON_MODULE "Build the pyopenvdb Python module" OFF)
> ```
> 
> to
> 
> ```
> option(OPENVDB_BUILD_PYTHON_MODULE "Build the pyopenvdb Python module" ON)
> ```

Hi,

I still get the same error when following your advice above. I get this:

python TestOpenVDB.py 
Traceback (most recent call last):
  File "TestOpenVDB.py", line 16, in <module>
    from studio import openvdb
ModuleNotFoundError: No module named 'studio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TestOpenVDB.py", line 18, in <module>
    import pyopenvdb as openvdb
ImportError: libboost_python37.so.1.68.0: cannot open shared object file: No such file or directory
 

Attached are my out files (I forgot to make them verbose this time) 
[out_cmake.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5569899/out_cmake.txt)
[out_make.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5569900/out_make.txt)
[out_makeinstall.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5569901/out_makeinstall.txt)
[CMakeLists.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5569902/CMakeLists.txt)

**Comment by Idclip** [comment]
Could you try running the following:
```
python -v -c "import pyopenvdb" &> pyvdb_out.txt
```

It will create a file `pyvdb_out.txt` which I'd like you to upload. If you get any terminal output from that provide that too.

Even though `pyopenvdb` is now being correctly installed you may still be picking up a broken version that exists on your system.

**Comment by andrewrgarcia** [comment]
> Could you try running the following:
> 
> ```
> python -v -c "import pyopenvdb" &> pyvdb_out.txt
> ```
> 
> It will create a file `pyvdb_out.txt` which I'd like you to upload. If you get any terminal output from that provide that too.
> 
> Even though `pyopenvdb` is now being correctly installed you may still be picking up a broken version that exists on your system.

[pyvdb_out.txt](https://github.com/AcademySoftwareFoundation/openvdb/files/5570142/pyvdb_out.txt)

**Comment by Idclip** [comment]
Okay I no longer believe this to be an issue with OpenVDB. The following in that file points to your python/boost installation being incomplete:

```
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb69ae3baf0>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libboost_python37.so.1.68.0: cannot open shared object file: No such file or directory
```

Can you please double check you have all the required dependencies installed, lists here: https://www.openvdb.org/documentation/doxygen/dependencies.html#depUsingAptGet

**Comment by andrewrgarcia** [comment]
> After installing all dependencies and building OpenVDB from https://github.com/AcademySoftwareFoundation/openvdb, I ran TestOpenVDB.py and got the following message:
> 
> **libboost_python37.so.1.68.0: cannot open shared object file: No such file or directory**
> 
> I ran "apt-file search libboost_python" in the Terminal to make sure the package was nowhere in my computer and it was not.
> I then ran an extensive "aptitude search boost 1.68" search in the Terminal and the closest named file to the requirement was **lib64boost-python37-1.68.0**. I installed it and then ran the TestOpenVDB.py file again but it still gave me the same message, seeing as it is not the same file. I did extensive searches of lib64 and libboost with the 1.68 1.67 and 1.71 extension and I could not find the elusive **libboost_python37.so.1.68.0** which python is asking for.
> 
> I am running Ubuntu 20.04 and Python 3.8.3, which are currently the most updated versions. Please help with this difficult issue, I would sincerely appreciate it. It is likely that I am not the only person with this problem right now.
> 
> Sincerely,
> Andrew

hi, yes I've gone through that whole list to check all dependencies are installed. I am quoting what I originally wrote; I've through the whole boost library; it appears libboost_python37.so.1.68.0 doesn't exist and that's what I need.

**Comment by Idclip** [comment]
The list I've linked is **not** the same list as on the readme, so I would run the following to be absolutely sure:

```
apt-get install libboost-python-dev
apt-get install libboost-numpy-dev
apt-get install python-dev
apt-get install python-numpy
```

Should that still fail you can try and install the complete boost dev package (libboost-all-dev) but it should not be necessary and, more likely, something else is wrong. Unfortunately I'm unable to suggest anything further.

**Comment by andrewrgarcia** [comment]
> The list I've linked is **not** the same list as on the readme, so I would run the following to be absolutely sure:
> 
> ```
> apt-get install libboost-python-dev
> apt-get install libboost-numpy-dev
> apt-get install python-dev
> apt-get install python-numpy
> ```
> 
> Should that still fail you can try and install the complete boost dev package (libboost-all-dev) but it should not be necessary and, more likely, something else is wrong. Unfortunately I'm unable to suggest anything further.

I went through all these steps, including libboost-all-dev. I am still getting the same error message. 
Anyways, I appreciate your effort. Thank you for trying to help me resolve the issue.

**Comment by petulka8s** [comment]
Hi,

I see you are using  _apt-get install libboost-numpy-dev_ to install **boost-numpy**.
Is there a way how to install boost-numpy via vcpkg?

Thank you.

**Comment by andrewrgarcia** [comment]
> Hi,
> 
> I see you are using _apt-get install libboost-numpy-dev_ to install **boost-numpy**.
> Is there a way how to install boost-numpy via vcpkg on Windows?
> 
> Thank you.

I don't use Windows I'm a Linux user (it's mentioned in the Issues title)

**Comment by ChloeZPan** [comment]
Have you solved this? I encountered the same issue.

**Comment by Idclip** [comment]
As our new boost minimum is 1.73 (from VDB 10) I'll close this. We'll hopefully be moving to pybind11 in the very near future, but please do create new issues if you encouter similar problems with 1.73

**Comment by Andrej730** [comment]
@andrewrgarcia have you managed to solve that issue? 
Just met this issue on py3.7, thought it's pyopenvdb related and posted it at https://github.com/theNewFlesh/docker_pyopenvdb/issues/7
Went through all mentioned dependecies installation - didn't helped.

**Comment by andrewrgarcia** [comment]
> @andrewrgarcia have you managed to solve that issue? 
> 
> Just met this issue on py3.7, thought it's pyopenvdb related and posted it at https://github.com/theNewFlesh/docker_pyopenvdb/issues/7
> 
> Went through all mentioned dependecies installation - didn't helped.
> 
> 
> 
> Also tried the solution below from [here](https://blog.csdn.net/otter1010/article/details/100524645) - didn't worked.
> 
> 
> 
> ```bash
> 
> wget https://boostorg.jfrog.io/artifactory/main/release/1.68.0/source/boost_1_68_0.tar.gz 
> 
> && tar zxf boost_1_68_0.tar.gz && cd boost_1_68_0 
> 
> && ./bootstrap.sh --with-python=/usr/bin/python3 
> 
> && sudo ./b2 install --with-python include="/usr/include/python3.7m"  --with-atomic  --with-log  --with-test --with-thread --with-date_time  --with-chrono`
> 
> 

Nope
