### ISSUE TITLE
BBox default values

### ISSUE THREAD

**Issue by ardabbour** [AcademySoftwareFoundation/openvdb#846]
In [`BBox.h`, line 146](https://github.com/AcademySoftwareFoundation/openvdb/blob/master/openvdb/openvdb/math/BBox.h#L146), the default definition of a bbox caught my eye:
```cpp
template<typename Vec3T>
inline
BBox<Vec3T>::BBox():
    mMin( std::numeric_limits<ElementType>::max()),
    mMax(-std::numeric_limits<ElementType>::max())
{
}
```
Seems that `-std::numeric_limits<ElementType>::max()` should be replaced with `std::numeric_limits<ElementType>::lowest()`. Also why is the minimum point set to the maximum value and vice-versa?

**Comment by Idclip** [comment]
Hello @ardabbour,

`max()` could indeed by replaced by `lowest()` (this was pre C++11). By default a `BBox` with no arguments is constructed with "invalid"/empty bounds, which it defines so long as `min>max`. As `-max() != lowest()` (for int types) its perhaps not worth changing.

```
/// @brief The default constructor creates an invalid bounding box.
BBox();
```
