### ISSUE TITLE
Crash in sdfToFogVolume

### ISSUE THREAD

**Issue by fkemmler** [AcademySoftwareFoundation/openvdb#847]
line 2231 in LevelSetUtil.h accesses internalNodes[0]. 
Calling this function with SDFs without internal nodes crash at that location. newTree->GetNodes(internalNodes); leaves the std::vector empty in that case.

Checking for internalNodes.size() > 0 before fixes the crash.

**Comment by Idclip** [comment]
Thanks @fkemmler, this should now be resolved

**Comment by fkemmler** [comment]
thanks a lot :)
