### ISSUE TITLE
Build issue vcpkg

### ISSUE THREAD

**Issue by Redwolf223** [AcademySoftwareFoundation/openvdb#852]
Hi, i'm currently getting an error when trying to install with vcpkg.

Here the full logs:

https://pastebin.com/wqpCHxk4

Thank you for the help!

**Comment by Idclip** [comment]
This is the wrong place to report this as it seems like an issue with one of vdbs dependencies (zlib) through vcpkg. Please open an issue at https://github.com/microsoft/vcpkg/issues
