### ISSUE TITLE
initialize() should use double-checked locking

### ISSUE THREAD

**Issue by BenFrantzDale** [AcademySoftwareFoundation/openvdb#869]
`openvdb::initialize()` in `openvdb.cc` is

```
namespace {
// Declare this at file scope to ensure thread-safe initialization.
Mutex sInitMutex;
bool sIsInitialized = false;
}

void
initialize()
{
    Lock lock(sInitMutex);
    if (sIsInitialized) return;

    ...
```
which means each call requires a mutex lock/unlock. There is an `uninitialize()` which also locks, although calling `uninitialize()` seems pretty dangerous in that anyone using anything that gets removed by `uninitialize()` will likely trigger UB. (For safe uninitialization to work, we'd probably be better off not to have a singleton!) If `uninitialize()` weren't available, we could just use `std::once_flag`.

All that said, the already-initialized ("hot") path for `initialize()` shouldn't require locking but should use double-checked locking <https://en.wikipedia.org/wiki/Double-checked_locking>. That is
```
namespace {
// Declare this at file scope to ensure thread-safe initialization.
Mutex sInitMutex;
std::atomic<bool> sIsInitialized{false};
}

void
initialize()
{
    if (sIsInitialized.load(std::memory_order_acquire)) return; // Hot path.
    Lock lock(sInitMutex);
    if (sIsInitialized.load(std::memory_order_relaxed)) return; // Someone else beat us to it while we were locking.

    ...
```

**Comment by Idclip** [comment]
This sounds reasonable to me! Would you mind making a PR?

**Comment by BenFrantzDale** [comment]
> This sounds reasonable to me! Would you mind making a PR?

Give me a few days. 

Thoughts about the safety of `uninitialize()`? It seems like it allows the caller to rip things out from under OpenVDB invoking UB. Is it actually used? I’m not volunteering to rearchitect that, but a non-singleton instance seems like the principled approach.

**Comment by Idclip** [comment]
I *think* use of `uninitialize()` is safe (at lest the behaviour is defined). init/uninit populate the file static factory registries that live in `Grid.cc`, `Metadata.cc` and `AttributeArray.cc`. Each of these has it's own lock separate from the lock that exists in `openvdb.cc`. If uninit isn't blocked and proceeds to try to clear one of the registries it will wait until that registry isn't in use. The clear methods also lock the registries. If something then tries to use these after uinit is called VDB will throw a runtime error as the registries will be empty. Any objects that have been created and persist after uninit has been called are still valid and can even be serialized. All these registries provide is a way to create VDB grids from their string type representations (predominantly used for file reading). So the defined behaviour for any subsequent use of the registries after uninit is called is a runtime exception.

**Comment by BenFrantzDale** [comment]
I see. Thanks for the clarification.

**Comment by BenFrantzDale** [comment]
https://github.com/AcademySoftwareFoundation/openvdb/pull/873
