### ISSUE TITLE
Building NanoVDB with latest OpenVDB

### ISSUE THREAD

**Issue by daniloarcidiacono** [AcademySoftwareFoundation/openvdb#897]
Hello,
I would like to try NanoVDB. It is my understanding that OpenVDB files cannot be loaded directly with NanoVDB, unless they are converted using OpenToNanoVDB tool. Since OpenToNanoVDB depends on OpenVDB (obviously) I need to build it as well. 

I noticed however that `feature/nanovdb` is about 100 commits behind `master`, and also the release of OpenVDB 7.2.0 is imminent.

Is `feature/nanovdb` going to be updated to the head of `master`? If not, are the dependencies listed in [OpenVDB 7.1.0 Documentation](https://www.openvdb.org/documentation/doxygen/dependencies.html) suitable for building OpenVDB from the `feature/nanovdb` branch?

Thanks

**Comment by daniloarcidiacono** [comment]
It seems that `feature/nanovdb` has been updated recently, and now OpenVDB 7.2.0 has higher minimum requirements for its dependencies. Too bad that the official documentation is NOT up to date, so after I've spent a lot of time gathering and building the whole dependency tree (OpenEXR, Blosc, zlib, lz4, Boost, oneTBB) I have to start from scratch again.

**Comment by jmlait** [comment]
feature/nanovdb should be periodically synced up to master.   It is currently a development branch so will vary with how it is tied to the main-line.  While we hope nanovdb is now ABI stable, it hasn't been officially brought into the main-line yet.

You should be able to use any OpenVDB 7.X build, not necessarily the one in feature/nanonvdb.   OpenVDB 7.X is ABI stable so any version of the library should be bitwise memory compatible with nanovdb's requirement.

Indeed, NanoVDB is header-only, so you can just copy it directly into your favorite OpenVDB 7.X build and use it directly without any extra dependency work.
