### ISSUE TITLE
[BUG] Minor range bug in tools/LevelSetSphere.h

### ISSUE THREAD

**Issue by thinks** [AcademySoftwareFoundation/openvdb#943]
I noticed a small issue with the range used with tbb::parallel_for in tools/LevelSetSphere.h. 

Refer to the attached file 
[vdb_tbb.pdf](https://github.com/AcademySoftwareFoundation/openvdb/files/5890339/vdb_tbb.pdf)
for more information. Essentially, there is an off-by-one error in a loop, causing overlap between chunks. This in and of itself might not be a huge deal, but this code is referenced in the documentation, which is slightly confusing.

**Comment by kmuseth** [comment]
Hi Tommy,

Great to hear from you - long time! Thanks for your bug-report. I glanced
at it and it sure looks like you discovered a legit bug. I'll study it some
more and get back to you.

cheers,
Ken

**Comment by thinks** [comment]
Hi Ken!

Hope you are doing well! :) I'm back in VFX after ~8 years in medtech
(radiotherapy). So much fun to be making pretty pictures again. As I'm sure
many have told you before OpenVDB is awesome, it's just insane what can be
done with it.

My suggested fix would be to change it like this:

// make end exclusive
for (i = r.begin(); i < r.end(); ++i) {
  // do stuff
}

// make end exclusive in range construction too.
tbb::parallel_for({imin, imax + 1});


Very simple stuff, but hard to find since no test will discover it! :)

Cheers,

T

**Comment by Idclip** [comment]
Fixed as of https://github.com/AcademySoftwareFoundation/openvdb/pull/1238
