### ISSUE TITLE
[BUILD]building failed for WSL2

### ISSUE THREAD

**Issue by Neversrd** [AcademySoftwareFoundation/openvdb#947]
### Environment
**Operating System:** WSL2/Ubuntu 20.04.1 LTS
**Version / Commit SHA:** openvdb 8.0.0 release
**CMake Version:** 3.16.3
**Compiler:** gcc 9.3.0

### Describe the problem
Hi there, I tried to build on WSL2 but it failed with these log:

>![image](https://user-images.githubusercontent.com/16793915/106470405-66307800-64db-11eb-9bee-37f32eb5344f.png)
...
/opt/intel/oneapi/tbb/2021.1.1/env/../include/tbb/../oneapi/tbb/partitioner.h:216:13: error: no matching function for call to ‘openvdb::v8_0::tree::LeafManager<const openvdb::v8_0::tree::Tree<openvdb::v8_0::tree::RootNode<openvdb::v8_0::tree::InternalNode<openvdb::v8_0::tree::InternalNode<openvdb::v8_0::tree::LeafNode<long int, 3>, 4>, 5> > > >::LeafRange::LeafRange(openvdb::v8_0::tree::LeafManager<const openvdb::v8_0::tree::Tree<openvdb::v8_0::tree::RootNode<openvdb::v8_0::tree::InternalNode<openvdb::v8_0::tree::InternalNode<openvdb::v8_0::tree::LeafNode<long int, 3>, 4>, 5> > > >::LeafRange&, tbb::detail::d0::split)’
  216 |             new(my_pool.begin()+prev) T(my_pool.begin()[my_head], detail::split()); // do 'inverse' split
...
![image](https://user-images.githubusercontent.com/16793915/106470537-8d874500-64db-11eb-95d6-66eba2b3010c.png)
...
/opt/intel/oneapi/tbb/2021.1.1/env/../include/tbb/../oneapi/tbb/parallel_for.h:65:27: error: no matching function for call to ‘openvdb::v8_0::tree::LeafManager<const openvdb::v8_0::tree::Tree<openvdb::v8_0::tree::RootNode<openvdb::v8_0::tree::InternalNode<openvdb::v8_0::tree::InternalNode<openvdb::v8_0::tree::LeafNode<openvdb::v8_0::math::Vec3<float>, 3>, 4>, 5> > > >::LeafRange::LeafRange(openvdb::v8_0::tree::LeafManager<const openvdb::v8_0::tree::Tree<openvdb::v8_0::tree::RootNode<openvdb::v8_0::tree::InternalNode<openvdb::v8_0::tree::InternalNode<openvdb::v8_0::tree::LeafNode<openvdb::v8_0::math::Vec3<float>, 3>, 4>, 5> > > >::LeafRange&, tbb::detail::d0::split)’
   65 |         my_allocator(alloc) {}
...

After searching on Google and StackOverflow, I guess this issue is caused by the mismatch of type of arguments (just like this [post](https://stackoverflow.com/questions/38461296/tbb-parallel-for-compile-error)), but I'm not sure and don't know how to fix it.

I believe I followed your instructions in readme and configured properly. Below are log for cmake:
![image](https://user-images.githubusercontent.com/16793915/106469828-c246cc80-64da-11eb-944c-7648b03ce11e.png)

Regards,
Li

**Comment by Idclip** [comment]
I suspect this is due to API changes in TBB 2021, otherwise known as intel oneAPI. The 2021 release of TBB is significantly different to prior versions and we don't currently test against it. This is on the todo list - if possible I'd recommend using an earlier version of TBB (2020, 2019 or 2018).

See also https://github.com/AcademySoftwareFoundation/openvdb/issues/932

**Comment by Neversrd** [comment]
> I suspect this is due to API changes in TBB 2021, otherwise known as intel oneAPI. The 2021 release of TBB is significantly different to prior versions and we don't currently test against it. This is on the todo list - if possible I'd recommend using an earlier version of TBB (2020, 2019 or 2018).
> 
> See also #932

Thank you! I switched to TBB 2020 and succeeded.
