### ISSUE TITLE
Pyopenvdb.pyd in version 8.0.0 versus pyopenvdb.dll in version 7.0.0

### ISSUE THREAD

**Issue by petulka8s** [AcademySoftwareFoundation/openvdb#981]
### Environment
**Operating System:** (e.g. Windows 2019, macOS-10.15, Linux CentOS 7.4)
**Version / Commit SHA:** (e.g VDB 7.2, SHA: 1a2b3c4d5e...)
**CMake Version:** (e.g. 3.18)
**Compiler:** (e.g. gcc 10, msvc 2019)

Hi,

I am able to build shared libraries for **OpenVDB 8.0.0** with python 3.9 and numpy.
It creates **openvdb.dll** and **pyopenvdb.pyd** which I am able to load into Python and call functions like vdb.FloatGrid().

The problem is that I need to connect this library with Blender which uses **OpenVDB 7.0.0**.

So I download older version of openvdb, but that version doesn't have python extension module.
It has just **pyopenvdb.dll** file. Is it correct? In older version there wasn't openvdb.pyd or it is my fault?

If it is correct, do you have any advices how can I work with pyopenvdb.dll in Python?
If I use _vdb = cdll.LoadLibrary("pyopenvdb.dll")_, I still can't call vdb.FloatGrid().

Is there possibility how to create in CMake from openvdb 8.0.0 -> openvdb 7.0.0?

Thank you for advices.

**Comment by Idclip** [comment]
Hello @petulka8s,

You can sometimes use newer versions of OpenVDB with previous versions **so long as you are building the core library with matching ABI.** This might also depend on how blender have exposed VDB symbols, but it's probably worth a shot. The default ABI for OpenVDB is its major version number i.e. for `7.x.x`, it's `7`. You can set this when building your version of OpenVDB 8.0.0 with:

```
cmake -DOPENVDB_ABI_VERSION_NUMBER=7 ..
```

You'll need to double check that this is indeed the same ABI that blender are building with (they could be using an older ABI and still be building VDB `7.x.x`), but this might allow you to continue to use OpenVDB `8.x.x`.

**Comment by Idclip** [comment]
Closing, please reopen if you still have questions.
