### ISSUE TITLE
[BUG] OpenVDB does not compile with blosc 1.14.2

### ISSUE THREAD

**Issue by treepleks** [AcademySoftwareFoundation/openvdb#991]
### Environment
**Operating System:** (e.g. Windows 2019, macOS-10.15, Linux CentOS 7.4) Ubuntu Bionic
**Version / Commit SHA:** (e.g VDB 7.2, SHA: 1a2b3c4d5e...) OpenVDB7.1
**CMake Version:** (e.g. 3.18) 3.15.4
**Compiler:** (e.g. gcc 10, msvc 2019) gcc6

### Describe the problem
(A clear and concise description of the encountered issue.)

At line 2481 of openvdb/openvdb/unittest/TestFile.cc, there is a test on c-blosc version to decide if a cast is needed (or not). The current version is compared to 1.15.

But the cast is already needed for 1.14. The line should therefore be changed to:

#if BLOSC_VERSION_MAJOR > 1 || (BLOSC_VERSION_MAJOR == 1 && BLOSC_VERSION_MINOR >= 14)

### To Reproduce

Setup a fresh Ubuntu bionic machine and try to compile POpenVDB with tests.

### Additional context
(Add any other context about the problem here.)

**Comment by Idclip** [comment]
Hey @treepleks thanks for reporting. As of OpenVDB 9.0.0 we've bumped our proposed new blosc minimum to 1.17.0 so I'm going to close this
